### ISSUE TITLE
Ignore Alterts during specific times

### ISSUE THREAD

**Issue by rusitschka** [oetiker/SmokePing#100]
I have some devices which turn off for some hours during night. I'd like to have them fire alerts during their online hours but not during their offline hours. I didn't find a way to do that through configuration. Any ideas/suggestions?

**Comment by 4f96a64d** [comment]
I'm sure you could cron something up using an include file with different alerting parameters. Wouldn't be pretty, but it would probably work.

Someone please correct me if I'm wrong, but I don't think there's facility for this within the software.

**Comment by Strykar** [comment]
Yea, a quick dirty hack would be to have two Smokeping's configs, and have a shell script reload Smokeping with each at the time required via cron or systemd.
