### ISSUE TITLE
alerts template

### ISSUE THREAD

**Issue by motifmark** [oetiker/SmokePing#103]
Hi. i'm currently running smokeping on a RHEL 7 server right now. Don't have an issues with monitoring and currently receiving alerts whenever there is an issue. However, we are advised to edit the template. Is there a way to edit the template? Below is a screenshot from an alert we just received.

![image](https://user-images.githubusercontent.com/34311256/33668800-b7b3388a-dadb-11e7-8cea-1d6213aad6f4.png)

**Comment by oetiker** [comment]
this is not a template unfortunately ... 

https://github.com/oetiker/SmokePing/blob/44682b6d3aec8d2063adae4dca1ce251c44e2fed/lib/Smokeping.pm#L1880
