### ISSUE TITLE
Alerts HELP

### ISSUE THREAD

**Issue by motifmark** [oetiker/SmokePing#104]
I'm receiving rtt alerts but some of my alerts when it comes to loss are not sending via smtp. The most important alert needed for our system is when a server is down, it needs to send an email right away. Below are my current alerts for smokeping. 

![image](https://user-images.githubusercontent.com/34311256/33782628-68a232b8-dc94-11e7-98b5-5a96d1f7ca91.png)

Kindly let me know if there is something wrong that needs to be fixed.

**Comment by oetiker** [comment]
the way you wrote it, the alerts will require a system to be offline for 2 rounds to trigger an alert

**Comment by motifmark** [comment]
Hi, I have tried to turn off the system for an hour but didn't receive any alerts. How do I know the interval or the time for each alerts? Btw, I have set the step by 60 and ping by 20.

**Comment by oetiker** [comment]
note that this rule will only detect the transition ... AND you also have to link the alert to the individual target you want to monitor

**Comment by motifmark** [comment]
So I can't mix alerts for RTT and loss for a group? 
![image](https://user-images.githubusercontent.com/34311256/33843788-4d0a884c-ded9-11e7-9f12-feebd6b652a8.png)
If I have multiple servers running with the same settings, I need to map each server with the same alerts?

**Comment by oetiker** [comment]
if you want the same alerts ... or actually you can set them higher up in the tree and they will get inherited.

**Comment by motifmark** [comment]
I have tried to set these alerts on a server.
![image](https://user-images.githubusercontent.com/34311256/33847579-f487bb9c-dee5-11e7-91ac-711632e48e7e.png)
And after 6 mins (step 180 ping 20)
I still don't have any alerts receive via email. I have also tried setting alert on each server that I want to test but still no progress. I'm not really sure right now what I'm doing, from my understanding each rounds using the step will trigger the alert if it matches right? Please, I really need some help with alerts.
