### ISSUE TITLE
SmokePing FAQ

### ISSUE THREAD

**Issue by mcdarren** [oetiker/SmokePing#11]
After having been on the smokeping-users mailing list for a while now, I've noticed that there are a few questions that come up over and over again, for example:
- "Why do I see the smokeping source in my web browser?"
- "My slave seems running ok but there is no data showing up in the graphs!"
- etc..

So it's probably worth adding a FAQ section to the documentation to cover these commonly asked questions?

People could then simply be directed to this when appropriate.

**Comment by sundialcommunications** [comment]
The list-serv isn't very searchable, while this is. This would actually be a better place to field these sorts of answers if you didn't want to be answering the same questions over and over again.

**Comment by sundialcommunications** [comment]
And on that note, running Ubuntu Server 14.04 LTS (HVM) on Amazon EC2 and running into the same issue.  Upon executing smokeping, I get the error" "ERROR: loading smokeping configuration file /usr/sbin/../etc/config: No such file or directory"

**Comment by oetiker** [comment]
we do have a FAQ page on https://github.com/oetiker/SmokePing/wiki/FAQ please add to it

**Comment by sundialcommunications** [comment]
Running "smokeping --config /etc/smokeping/config" worked for me.

**Comment by ramgarden** [comment]
Where do we set it to autorun on boot so that it uses --config /etc/smokeping/config each time?

**Comment by Strykar** [comment]
@ramgarden Your distro's package should define that. What OS?

**Comment by speculatrix** [comment]
I stumbled on this when trying to debug why a slave's measurements weren't being recorded in graphs.
Why doesn't the master send a syslog message when the rrdupdate fails?

**Comment by MrTiptop** [comment]
Hello, i am struggling to setup a master (setup and working correctly) and multiple slave servers.
Master server is working perfect. Slave is working in Mode=slave. when i run smokeping --debug i get no errors.

"Smokeping version 2.006011 successfully launched.                                                                                                                        
Not entering multiprocess mode with '--debug'. Use '--debug-daemon' for that.                                                                                            
FPing: probing 1 targets with step 300 s and offset 226 s.                                                                                                               
FPing: Executing /usr/bin/fping -C 20 -q -B1 -r1 -i10 localhost                                                                                                          
FPing: Got fping output: 'localhost : 0.03 0.03 0.03 0.05 0.04 0.03 0.03 0.04 0.03 0.05 0.03 0.04 0.05 0.04 0.05 0.03 0.05 0.03 0.03 0.05'                               
Calling RRDs::update(/var/lib/smokeping/Local/LocalMachine.rrd --template uptime:loss:median:ping1:ping2:ping3:ping4:ping5:ping6:ping7:ping8:ping9:ping10:ping11:ping12:p
ing13:ping14:ping15:ping16:ping17:ping18:ping19:ping20 1533720776:U:0:4.0000000000e-05:3.0000000000e-05:3.0000000000e-05:3.0000000000e-05:3.0000000000e-05:3.0000000000e-
05:3.0000000000e-05:3.0000000000e-05:3.0000000000e-05:3.0000000000e-05:3.0000000000e-05:4.0000000000e-05:4.0000000000e-05:4.0000000000e-05:4.0000000000e-05:5.0000000000e
-05:5.0000000000e-05:5.0000000000e-05:5.0000000000e-05:5.0000000000e-05:5.0000000000e-05)"

i have followed these instructions step by step -> https://bejoybkn.wordpress.com/2012/06/28/installing-and-configuring-smokeping-server-and-clients-in-an-easy-way/

1. So how do confirm my slave is running in "Slave mode"?
2. How do i confirm my slave has pulled the config from the master?
3. what steps do i need to follow to troubleshoot why my slave is not updating my .rrd file on the master?

thanks for the help.

**Comment by MrTiptop** [comment]
So, i have checked the apache2/error.log file and i see nothing in there.. even when trail -f, nothing... i have also killed the smokeping process on the slave, started it with "--debug-daemon" and also tail the apache2/error.log file and i still see nothing.. Any ideas? 

Question: If the slave has correctly pulled the config from master, should i not see in the debug log the slave polling everything i have configured in the master? 

1. How can i confirm the slave have married up correctly with the master? What command should i run/what should i look for in the logs? Which logs?

**Comment by deajan** [comment]
Hi,
Want to share my solution for eliminating the write permissions problem from slave on master.
I have my data directory in /opt/smokeping/data which is not writable by apache.
Since I need the slave to write to the master, I've setup a directory in the virtualhost like
```
mkdir /var/www/smokeping.host/_dyn
chown apache /var/www/smokeping.host/_dyn
chmod 770 /var/www/smokeping.host/_dyn
```

Setting the following in smokeping configuration will then allow the slave to write to master:
```
*** General ***
...
dyndir = /var/www/smokeping.host/_dyn
precreateperms = 02775
```

The daemon itself has to run as group apache in order to be able to use permissions 775 instead of 777.
Example of a deamon config for systemd alllowing to run as group apache:
```
[Unit]
Description=Latency Logging and Graphing System
After=syslog.target network.target

[Service]
ExecStart=/opt/smokeping/bin/smokeping --config=/opt/smokeping/etc/config --logfile=/var/log/smoke.log --nodaemon
ExecReload=/bin/kill -HUP $MAINPID
StandardError=syslog
Group=apache

[Install]
WantedBy=multi-user.target
```

**Comment by Strykar** [comment]
I created a script so users can review the ACLs on their smokeping `imgcache`, `datadir` and `piddir` and hopefully fix the permissions/ACLs - [smokeperms.sh](https://gist.github.com/Strykar/0d6666520a481d777c7fc0969841c86c)
