### ISSUE TITLE
fping 4.0 causes pings to fail

### ISSUE THREAD

**Issue by hildeb** [oetiker/SmokePing#112]
When using smokeping with fping 4.0 I noticed the graphs being empty. I then checked the invocation of fping and found this command line:

```
/usr/bin/fping -C 10 -q -B1 -r1 -t2000 -i10 k350.charite.de k700.charite.de
/usr/bin/fping: warning: timeout (-t) value larger than period (-p) produces unexpected results

```
Switching back to fping 3.13 made everything work again.
Using smokeping 2.6.11

**Comment by tfgm-bud** [comment]
@hildeb how did you install fping?  If from source, did you `setcap cap_net_raw+ep /usr/local/sbin/fping` ?

**Comment by tfgm-bud** [comment]
@hildeb, I can't reach the sites you are trying to ping, but the same command line with a different host works fine:

```
$ /usr/local/sbin/fping -v
/usr/local/sbin/fping: Version 4.0
/usr/local/sbin/fping: comments to david@schweikert.ch
$ sudo /usr/local/sbin/fping -C 10 -q -B1 -r1 -t2000 -i10 google.com
/usr/local/sbin/fping: warning: timeout (-t) value larger than period (-p) produces unexpected results
google.com : 32.4 32.3 32.3 32.3 32.3 34.5 32.3 32.2 32.2 32.3
```
Pretty sure the `warning` is was just a warning -- `fping` still should work. The P default is 1000 (one second).  Do you really need a 2 seconds timeout?

One other thing to try, if you haven't is running as the `smokeping` user:
```
sudo -u smokeping smokeping --debug
```
and when you are testing the fping command:
```
sudo -u smokeping  /usr/bin/fping -C 10 -q -B1 -r1 -t2000 -i10 k350.charite.de k700.charite.de
```
You may get different results based on that.

**Comment by hildeb** [comment]
# getcap /usr/bin/fping
/usr/bin/fping = cap_net_raw+ep

# ls -l /usr/bin/fping
-rwxr-xr-x 1 root root 48000 Jun 18  2017 /usr/bin/fping

# /usr/bin/fping -v
/usr/bin/fping: Version 4.0
/usr/bin/fping: comments to david@schweikert.ch

Trying again...

# /usr/bin/fping -C 10 -q -B1 -r1 -t2000 -i10 k350.charite.de k700.charite.de
/usr/bin/fping: warning: timeout (-t) value larger than period (-p) produces unexpected results
k350.charite.de : 1.04 1.04 1.20 29.48 1.08 1.24 1.13 1.14 1.01 1.05
k700.charite.de : 2.74 2.83 2.34 1.87 1.55 1.50 10.28 9.29 8.06 7.29

Hmm, seems to be working OK.

**Comment by NoifP** [comment]
Thanks for posting - I had the same issue on Ubuntu 18.04.

fping was not working on a new smokeping slave with the Ubuntu 18.04 fping package (version 4.0).

`setcap cap_net_raw+ep /usr/bin/fping` fixed it right up and now it is happy.
