### ISSUE TITLE
doesn't retry if probes exit abnormally

### ISSUE THREAD

**Issue by tycho** [oetiker/SmokePing#114]
I had set a filesystem quota on the /var/lib/smokeping directory, deliberately making it too small. Smokeping eventually failed with this:

```
Apr 10 22:25:37 elbereth smokeping[3897]: can't create /var/lib/smokeping/__sortercache/new.FPing6: Disk quota exceeded at /usr/lib/Smokeping.pm line 1827.
Apr 10 22:25:37 elbereth smokeping[3897]: Child process 14612 (probe FPing6) exited unexpectedly with status 31232.
Apr 10 22:26:40 elbereth smokeping[3897]: can't create /var/lib/smokeping/__sortercache/new.FPing: Disk quota exceeded at /usr/lib/Smokeping.pm line 1827.
Apr 10 22:26:40 elbereth smokeping[3897]: Child process 14611 (probe FPing) exited unexpectedly with status 31232.
```

Even though I had resolved the quota issue shortly after this (increased the quota size), it stopped trying that probe until I restarted smokeping manually several hours later.

So it seems that smokeping is considering an unexpected exit code a permanent failure, when it should actually probably just try again on the next polling attempt.

**Comment by tycho** [comment]
My stupid hack workaround is below. It basically zaps the remaining probes before restarting all of them. I wouldn't recommend using this change because it'll cause a single repeatedly failing probe to prevent the remainder of them from running properly (because they'll repeatedly get killed).

```diff
diff --git a/lib/Smokeping.pm b/lib/Smokeping.pm
index d291143..6122517 100644
--- a/lib/Smokeping.pm
+++ b/lib/Smokeping.pm
@@ -4365,6 +4365,7 @@ RESTART:
                         exit 0;
                 }
         };
+        my $gothup = 0;
         $SIG{CHLD} = sub {
                 while ((my $dead = waitpid(-1, WNOHANG)) > 0) {
                         my $p = $probepids{$dead};
@@ -4372,9 +4373,9 @@ RESTART:
                         do_log("Child process $dead (probe $p) exited unexpectedly with status $?.")
                                 unless $exiting or $reloading;
                         delete $probepids{$dead};
+                        $gothup = 1;
                 }
         };
-        my $gothup = 0;
         $SIG{HUP} = sub {
                 do_debuglog("Got HUP signal.");
                 $gothup = 1;
```

A better solution would notice that a particular is dead and restart it, without all the song and dance of reloading the config files and killing the other child processes.

**Comment by mendrika** [comment]
Had the exact same issue for three days in a row.
Cannot figure out, why they did not correct this behaviour
