### ISSUE TITLE
Forbidden You don't have permission to access /smokeping on this server.

### ISSUE THREAD

**Issue by Ericwonne** [oetiker/SmokePing#115]
ForbiddenYou don't have permission to access /smokeping on this server.

I search on google for a lot of answers but none did fix this. It seems I have configured it right, everything is okay in httpd.conf, but when access it through the browser, it gives  a Forbidden message.
And I am a niewbie on smokeping using, I even have little idea of how it works, since I just began use it a day ago, and the most frustrating thing is everytime I fixed a problem it comes another and this time I seem to be in a dilemma.
Anyone in this open-source world would you please give me a hand on this.
Reach me at my email(ericwong1996@gmail.com) or through this.
--

**Comment by asterissco** [comment]
Hi!
Try to do this
root@prueba:~# vim /etc/apache2/conf-available/smokeping.conf

- Alias /smokeping /usr/share/smokeping/www
+ Alias /smokeping /usr/share/smokeping

- <Directory "/usr/share/smokeping/www">
+ <Directory "/usr/share/smokeping">

Restart web-server

**Comment by Ericwonne** [comment]
Thanks a lot. I got this done.

**Comment by DelfrCorp** [comment]
It looks like copying the file over to www worked for you but it did not work out for me on CentOS 7 (though I believe many people running RedHat or Fedora may encounter the same issue).
I discovered that the issue lied with newer versions of httpd and the base smokeping.conf deployed with the smokeping package when running "yum smokeping install".

What did work out for me was editing out the values preceded by "###"" and adding the   "Require all granted" in /etc/httpd/conf.d/smokeping.conf:

<Directory "/usr/share/smokeping" >
  Require all granted
  ###Order deny,allow
  ###Deny from all
  ###Allow from 127.0.0.1
</Directory>

<Directory "/var/lib/smokeping" >
  Require all granted
  ###Order deny,allow
  ###Deny from all
  ###Allow from 127.0.0.1
</Directory>

**Comment by lelutin** [comment]
@oetiker this question seems like it was answered. just prodding you so you can close it.
