### ISSUE TITLE
Recent version of tcpping supporting newer traceroute

### ISSUE THREAD

**Issue by deajan** [oetiker/SmokePing#116]
Hello,

I just installed a fresh version of smokeping 2.7.2 and had good headaches getting the tcpping probe to work.
After messing around with the latest tcpping version, I noticed that recent traceroute binaries don't work anymore with that script.

I finally forked the script, and made it work with recent versions of traceroute on Linux and BSD, among a list of other small improvements, and dropped tcptraceroute script dependency.

Would you care to update the smokeping internet site with the link where to find that recent tcpping version ?

https://github.com/deajan/tcpping

Thanks for your hard work on smokeping.
Best regards.

**Comment by deajan** [comment]
I agreed with Richard van den Berg to be the new maintainer of the script some months ago.
Since then, I've done some small work on that script in order to make it work in most usecases, and recent OSes.
Would you mind updating the link in https://oss.oetiker.ch/smokeping/probe/TCPPing.en.html to the new repository ?
https://github.com/deajan/tcpping or the direct link https://raw.githubusercontent.com/deajan/tcpping/master/tcpping

Thanks.

**Comment by woosley** [comment]
I met the same issue and it took me sometime to find this page to solve the issue, it would be great if the webpage can be updated.

**Comment by deajan** [comment]
@oetiker Would you mind to update that link ?

**Comment by oetiker** [comment]
the website is generated :) can you PR for the TCPPing probe ? I will then run the update

**Comment by deajan** [comment]
Sure, I would never have guessed so. PR ready at https://github.com/oetiker/SmokePing/pull/165

**Comment by oetiker** [comment]
thanks. merged and updated website
