### ISSUE TITLE
Update readme / FAQ - Smokeping 2.7.2 complie issues on Ubuntu 14.04.x / 16.04.x

### ISSUE THREAD

**Issue by agail** [oetiker/SmokePing#118]
Hi,

Just downloaded smokeping-2.7.2 and tried to compile. Got some errors due to missing dependencies.
In order to successfully compile, follow this additional steps before running make or make install

14.04: 
You need to install libssl-dev (Secure Sockets Layer toolkit - development files) 

16.04: 
You need to install libssl-dev (Secure Sockets Layer toolkit - development files) and libnet-ssleay-perl (Perl module for Secure Sockets Layer (SSL)

Thanks for a great tool!
\Agail

**Comment by mergeMarc** [comment]
Not working on 18.04 LTS, even after i installed libssl-dev and ibnet-ssleay-perl.

```
Making install in thirdparty
make[1]: Entering directory '/home/user/smokeping-2.7.2/thirdparty'
echo "If the moduile install hangs, this may be because one of the modules expects you to press [return] without telling you ... just do it!"
If the moduile install hangs, this may be because one of the modules expects you to press [return] without telling you ... just do it!
  GEN      touch
FCGI is up to date. (0.78)
CGI is up to date. (4.38)
CGI::Fast is up to date. (2.13)
Config::Grammar is up to date. (1.12)
Socket6 is up to date. (0.28)
! Couldn't find module or a distribution Mozilla::CA
! Installing Net::SSLeay failed. See /home/user/smokeping-2.7.2/thirdparty/work/1543579067.27766/build.log for details. Retry with --force to force install it.
! Installing the dependencies failed: Module 'Mozilla::CA' is not installed, Module 'Net::SSLeay' is not installed
! Bailing out the installation for IO-Socket-SSL-2.056.
Digest::HMAC_MD5 is up to date. (1.01)
Net::Telnet is up to date. (3.04)
Net::OpenSSH is up to date. (0.77)
Net::SNMP is up to date. (v6.0.1)
Net::LDAP is up to date. (0.65)
Net::DNS is up to date. (1.15)
IO::Pty is up to date. (1.12)
LWP is up to date. (6.33)
Authen::Radius is up to date. (0.26)
Path::Tiny is up to date. (0.104)
Makefile:410: recipe for target 'touch' failed
make[1]: *** [touch] Error 123
make[1]: Leaving directory '/home/user/smokeping-2.7.2/thirdparty'
Makefile:363: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
```

I'm reverting to 2.7.1 for now.

**Comment by oetiker** [comment]
can you try

`touch PERL_MODULES`

**Comment by mergeMarc** [comment]
After creating the "PERL_MODULES" file, the error message changed:
```
Making install in thirdparty
make[1]: Entering directory '/home/user/smokeping-2.7.2/thirdparty'
echo "POPULATING OUR LOCAL micro CPAN"
POPULATING OUR LOCAL micro CPAN
  GEN      CPAN/touch
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    15  100    15    0     0     73      0 --:--:-- --:--:-- --:--:--    73
syntax error at - line 1, near "404:"
Execution of - aborted due to compilation errors.
Makefile:415: recipe for target 'CPAN/touch' failed
make[1]: *** [CPAN/touch] Error 255
make[1]: Leaving directory '/home/user/smokeping-2.7.2/thirdparty'
Makefile:363: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
```

What i find interesting about this error message is that a file with the name `touch` gets created in `thirdparty/CPAN/`. Don't know if this is expected behaviour.

**Comment by oetiker** [comment]
very odd .. just tested compilation here and it works fine

**Comment by oetiker** [comment]
aah just realized that I had not pushed the update to the cpanmin.us url ... get master and you shoud be all set

**Comment by mergeMarc** [comment]
Make install now works with master 👍

**Comment by mergeMarc** [comment]
Just want to add that even with the fix, the two packets (libssl-dev and libnet-ssleay-perl) still need to be installed manually beforehand for the installation to work. (Tested on another system with master)

**Comment by duomir** [comment]
> Make install now works with master 👍

Hello ,can you tell me how to do ,please?

**Comment by oetiker** [comment]
try 2.7.3

**Comment by duomir** [comment]
Thank you!, It's work fine. Use:sudo yum install perl-core

**Comment by thusithasumanadasa** [comment]
hi I've done as above mentioned. But now I'm getting this error after `make install`. how to solve this.I'm trying to install smokeping 2.7.3
```
Makefile:299: recipe for target 'install-etcDATA' failed
make[2]: *** [install-etcDATA] Error 1
make[2]: Leaving directory '/opt/smokeping/etc'
Makefile:369: recipe for target 'install-am' failed
make[1]: *** [install-am] Error 2
make[1]: Leaving directory '/opt/smokeping/etc'
Makefile:363: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
```

**Comment by adnanbatara** [comment]
Smokeping installation issue: Net-SSLeay: SSLeay CPAN install crash on 'ld: cannot find -lz'

Reference: https://rt.cpan.org/Public/Bug/Display.html?id=127527

Solution: sudo apt-get install zlib1g-dev

Check for dpkg -l libnet-ssleay-perl libcrypt-ssleay-perl beforehand.
