### ISSUE TITLE
Edge trigger - sixth argument not present when alert is cleared

### ISSUE THREAD

**Issue by ricardoj-br** [oetiker/SmokePing#122]
I'm running Smokeping 2.6.11 on ubuntu 16.04 and when alert is configured for edgetrigger = yes the sixth argument is not present when alert is cleared.

It is present on alert is set. See bellow :

1532634650;webconnloss;Appliances.XYZ;loss: 100%, 100%, 100%;rtt: U, U, U;127.0.0.1;1
1532635353;webconnloss;Appliances.XYZ;loss: 100%, 100%, 0%;rtt: U, U, 96ms;127.0.0.1;

The file was created by this bash script :

#!/bin/bash
#
#The alert notifications and/or the programs executed are normally triggered every
#time the alert matches. If this variable is set to 'yes', they will be triggered
#only when the alert's state is changed, ie. when it's raised and when it's cleared.
#Subsequent matches of the same alert will thus not trigger a notification.
#
#When this variable is set to 'yes', a notification program (see the B<to> variable
#documentation above) will get a sixth argument, B<raise>, which has the value 1 if the alert
#was just raised and 0 if it was cleared.
#
#name-of-alert, target, loss-pattern, rtt-pattern, hostname, raise (edgetrigger)
#
now=`/bin/date +%s`
/bin/echo "$now;$1;$2;$3;$4;$5;$6" >> /home/smokeping/alert_up_down.txt

Is there any additional configuration that I missed ?

Thank you,

Ricardo Jorge

**Comment by ricardoj-br** [comment]
One can find a solution here : https://lists.oetiker.ch/pipermail/smokeping-users/2012-August/004890.html

The code for version I'm using ( 2.6.11 ) is : 

                                if ($edgetrigger) {
                                   exec $cmd,$_,$line,$loss,$rtt,$tree->{host}, ($what =~/raise/ ? 1 : 0);
                                } else {

I hope this help someone else. Regards,

Ricardo Jorge

**Comment by helpdeskdan** [comment]
>I hope this help someone else. Regards,

YES - yes it did, thank you so much Ricardo

**Comment by oetiker** [comment]
how about a PR ?

**Comment by FliesLikeABrick** [comment]
Spent some time today working out a problem with our PagerDuty integration that was caused by this.  I will look and see if my weak perl is up to the task of opening a PR for this.

**Comment by FliesLikeABrick** [comment]
PR open @oetiker

**Comment by FliesLikeABrick** [comment]
@oetiker  following up (the topic just came up again in our team's weekly code review), thanks.
