### ISSUE TITLE
Smokeping does not send mail

### ISSUE THREAD

**Issue by hgortega** [oetiker/SmokePing#123]
Hi there
I have smokeping working fine, it is graphing devices but it is not sending e-mail when alerts occurs. I have tested sendmail and it is working. I do not have logs about it in logs files. What is missing? Next is my config:

contact  = support@abcnnn.net
mailhost = srv1.abcnnn.net
sendmail = /usr/sbin/sendmail
# NOTE: do not put the Image Cache below cgi-bin
# since all files under cgi-bin will be executed ... this is not
# good for images.
imgcache = /var/www/smokeping/cache
imgurl   = cache
datadir  = /opt/smokeping/data
piddir  = /opt/smokeping/var
cgiurl   = http://some.url/smokeping.cgi
smokemail = /opt/smokeping/etc/smokemail.dist
tmail = /opt/smokeping/etc/tmail.dist
# specify this to get syslog logging
syslogfacility = local0
# each probe is now run in its own process
# disable this to revert to the old behaviour
# concurrentprobes = no

*** Alerts ***
to = name@abcnnn.net
from = smokeping@abcnnn.net

Note: abcnnn was changed for domain name.

Regards,

**Comment by Strykar** [comment]
What's the output of `tSmoke --testmail`?
See https://www.systutorials.com/docs/linux/man/1-tSmoke/

**Comment by cheapstaking** [comment]
Hi - im also having this issue - no mail is recieved and dead.letter file is generated for each message that doesnt get sent

tSmoke --testmail results in:
(c) 2003 Dan McGinn-Combs
ERROR: not sending mail to user@company.com, as all methodes failed
Sending a test mail to  user@company.com from smokealarm@company.com...done.

**Comment by pfworks** [comment]
I'm having the same issue. I can send mail by invoking sendmail directly, but tSmoke can't send mail.

**Comment by pfworks** [comment]
I got this to work. For whatever reason, 
} elsif ($cfg->{General}{sendmail} or -x "/usr/lib/sendmail"){             
        open (M, "|-") || exec (($cfg->{General}{sendmail} || "/usr/lib/sendmail
        print M $body;                                
        close M;
    } else {                      
        warn "ERROR: not sending mail to $to, as all methodes failed\n";    

wasn't picking up my definition of sendmail at "/usr/sbin/sendmail". So changing the /usr/lib to /usr/sbin fixed my email issue. Now, I can't get any alerts to happen, but at least I know it's not email...
