### ISSUE TITLE
Unable to install this repo

### ISSUE THREAD

**Issue by tonydm** [oetiker/SmokePing#130]
Hello, I have been working for the better part of week trying to install this repo, I'm wanting to install the latest version to play with and test against my other Smokeping deployments both standalone and Master/Slave.  However, I have been unsuccessful.  I have tried a number of OS Distros and versions (Centos6/7, Ubuntu 14.04, 16.04, 18.04).  I'm not a SysAdmin genus by any stretch but have managed to admin a small data center (primarily Centos/Ubuntu/SunOS) and services ranging from Motorola WiMAX, Sandvine, Allot, and any other service you can think of regarding network and communication services.  With that said, here's what I've found.  I've attempted to install many of the perl modules manually but have still failed.  I'm not sure what I am missing here.  I experience the same result  if I download the 2.7.2 source directly from https://oss.oetiker.ch/smokeping/pub/smokeping-2.7.2.tar.gz.  I show that result below as well.  If I'm missing something obvious, my apologies.  I've done some research on the PERL5LIB env variable, but haven't found anything conclusive and no path I've tried resolves the issue.

I'm using Docker as my testing platform.

**# Github repo install attempt**

docker run --rm -it --name smokeping-testing centos:latest bash

[root@d45cbee09189 SmokePing]# history
    1  yum update -y
    2  yum groupinstall 'Development Tools' -y
    3  yum install epel-release -y
    4  yum install git rrdtool rrdtool-perl  -y
    5  cd /tmp/
    6  git clone https://github.com/oetiker/SmokePing.git
    7  cd SmokePing/
    8  ./bootstrap 
    9  ./configure 
   10  /usr/bin/gmake install
   11  history

> [root@d45cbee09189 SmokePing]# ./configure 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '0' is supported by ustar format... yes
checking whether GID '0' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether to enable maintainer-specific portions of Makefiles... no
checking whether make supports nested variables... (cached) yes
checking for perl... /usr/bin/perl
checking for curl... /usr/bin/curl
checking for wget... no
checking for perl version greater than or equal to 5.10.1... ok
checking for sed... /usr/bin/sed
checking for grep... /usr/bin/grep
checking for echo... /usr/bin/echo
checking for ln... /usr/bin/ln
checking for cp... /usr/bin/cp
checking for rm... /usr/bin/rm
checking for rmdir... /usr/bin/rmdir
checking for mkdir... /usr/bin/mkdir
checking for find... /usr/bin/find
checking for sendmail... /path/to/sendmail
checking for gnroff... /usr/bin/gnroff
checking for gnumake... no
checking for gmake... /usr/bin/gmake
checking checking for gnu make availablility... /usr/bin/gmake is GNU make
checking checking for RRDs perl module... Ok
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating bin/Makefile
config.status: creating doc/Makefile
config.status: creating htdocs/Makefile
config.status: creating etc/Makefile
config.status: creating lib/Makefile
config.status: creating thirdparty/Makefile
config.status: creating etc/config.dist

** Ready to install Smokeping ******************************

   Settings:

     PERL5LIB = not set
     PERL = /usr/bin/perl

   The Smokeping Makefiles use GNU make functionality.
   Continue installation with

     /usr/bin/gmake install

[root@d45cbee09189 SmokePing]#

>[root@d45cbee09189 SmokePing]# /usr/bin/gmake install
Making install in thirdparty
gmake[1]: Entering directory /tmp/SmokePing/thirdparty
echo "POPULATING OUR LOCAL micro CPAN"
POPULATING OUR LOCAL micro CPAN
  GEN      CPAN/touch
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  295k  100  295k    0     0   519k      0 --:--:-- --:--:-- --:--:--  518k
**Cant locate ExtUtils/Manifest.pm** in @INC (@INC contains: FatPacked::17730440=HASH(0x10e8b88) /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at - line 132.
gmake[1]: *** [CPAN/touch] Error 1
gmake[1]: Leaving directory /tmp/SmokePing/thirdparty
gmake: *** [install-recursive] Error 1

**# Source install attempt**

>[root@d45cbee09189 tmp]# curl -L -o smokeping-2.7.2.tar.gz https://oss.oetiker.ch/smokeping/pub/smokeping-2.7.2.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4506k  100 4506k    0     0   421k      0  0:00:10  0:00:10 --:--:--  481k
[root@d45cbee09189 tmp]# tar -zxvf smokeping-2.7.2.tar.gz 
[root@d45cbee09189 tmp]# cd smokeping-2.7.2
...
[root@d45cbee09189 smokeping-2.7.2]# ./configure 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '0' is supported by ustar format... yes
checking whether GID '0' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether to enable maintainer-specific portions of Makefiles... no
checking whether make supports nested variables... (cached) yes
checking for perl... /usr/bin/perl
checking for curl... /usr/bin/curl
checking for wget... no
checking for perl version greater than or equal to 5.10.1... ok
checking for sed... /usr/bin/sed
checking for grep... /usr/bin/grep
checking for echo... /usr/bin/echo
checking for ln... /usr/bin/ln
checking for cp... /usr/bin/cp
checking for rm... /usr/bin/rm
checking for rmdir... /usr/bin/rmdir
checking for mkdir... /usr/bin/mkdir
checking for find... /usr/bin/find
checking for sendmail... /path/to/sendmail
checking for gnroff... /usr/bin/gnroff
checking for gnumake... no
checking for gmake... /usr/bin/gmake
checking checking for gnu make availablility... /usr/bin/gmake is GNU make
checking checking for RRDs perl module... Ok
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating bin/Makefile
config.status: creating doc/Makefile
config.status: creating htdocs/Makefile
config.status: creating etc/Makefile
config.status: creating lib/Makefile
config.status: creating thirdparty/Makefile
config.status: creating etc/config.dist

** Ready to install Smokeping ******************************

   Settings:

     PERL5LIB = not set
     PERL = /usr/bin/perl

   The Smokeping Makefiles use GNU make functionality.
   Continue installation with

     /usr/bin/gmake install

[root@d45cbee09189 smokeping-2.7.2]# /usr/bin/gmake install
Making install in thirdparty
gmake[1]: Entering directory `/tmp/smokeping-2.7.2/thirdparty'
echo "If the moduile install hangs, this may be because one of the modules expects you to press [return] without telling you ... just do it!"
If the moduile install hangs, this may be because one of the modules expects you to press [return] without telling you ... just do it!
  GEN      touch
Can't locate ExtUtils/Manifest.pm in @INC (@INC contains: FatPacked::32930696=HASH(0x1f67b88) /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /tmp/smokeping-2.7.2/thirdparty/bin/cpanm line 132.
gmake[1]: *** [touch] Error 123
gmake[1]: Leaving directory `/tmp/smokeping-2.7.2/thirdparty'
gmake: *** [install-recursive] Error 1

**# Install attempt on Ubuntu 16.04 from git repo**
docker run --rm -it --name smokeping-testing ubuntu:16.04 bash

...
>** Ready to install Smokeping ******************************

   Settings:

     PERL5LIB = not set
     PERL = /usr/bin/perl

   The Smokeping Makefiles use GNU make functionality.
   Continue installation with

     /usr/bin/make install

root@82b7c3b49412:/SmokePing# /usr/bin/make install
Making install in thirdparty
make[1]: Entering directory '/SmokePing/thirdparty'
echo "POPULATING OUR LOCAL micro CPAN"
POPULATING OUR LOCAL micro CPAN
  GEN      CPAN/touch
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  295k  100  295k    0     0   463k      0 --:--:-- --:--:-- --:--:--  463k
Successfully installed App-cpanminus-1.7044
1 distribution installed
  GEN      CPAN/touch
Successfully installed File-Which-1.22
! **Configure failed for OrePAN-0.08**. See /SmokePing/thirdparty/Ore/work/1539269014.5217/build.log for details.
1 distribution installed
Makefile:415: recipe for target 'CPAN/touch' failed
make[1]: *** [CPAN/touch] Error 1
make[1]: Leaving directory '/SmokePing/thirdparty'
Makefile:362: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

'

**Comment by oetiker** [comment]
You have to install perl-core on redhat to be able to build perl modules 

`yum install perl-core`

**Comment by tonydm** [comment]
@tobias - Thank you!  After more careful review, I do see that documented in, of all places, the docs/smokeping_install.pod file.  My apologies.  A reminder to be a little more thorough.

Regarding the similar Ubuntu distro failure.  As I continued my attempts I observed an obscure reference to 'unzip'.  Installing unzip resolved the error.
