### ISSUE TITLE
My smokeping slave 'rrd' files are not updating when run in master-slave mode...

### ISSUE THREAD

**Issue by KalyanKB** [oetiker/SmokePing#132]
Hi,
I am running smokeping slave with master url and shared secret "./smokeping start --cache-dir=/opt/smokeping/data --master-url=http://smokeping-master-url/cgi-bin/smokeping.fcgi --shared-secret=/opt/smokeping/etc/slavesecret.conf"
But the rrd files of the slave is not updating.I didn't get the data of polling from slave.
Where can i check the fault?

Thanks in Advance

**Comment by Strykar** [comment]
https://github.com/oetiker/SmokePing/wiki/Script-to-check-smokeping-webserver-ACLs
