### ISSUE TITLE
Unable to Zoom or Crop Graphs when upgraded to 2.7.2

### ISSUE THREAD

**Issue by Gregged** [oetiker/SmokePing#134]
Installed: 2.6.11-3
Candidate: 2.7.2-3
OS: Debian 8

When I upgrade from 2.6 to 2.7 I lose my ability to upgrade or zoom the graphs. I did not get any upgrade errors, otherwise from this everything else works perfectly.

**Comment by jiberan** [comment]
@Gregged did you manage to solve it? I'm running into the same issue...

**Comment by Gregged** [comment]
No, I am sorry man, wasted a lot of time trying to solve.
    On Friday, 1 November 2019, 17:24:47 GMT-5, jiberan <notifications@github.com> wrote:  
 
 
@Gregged did you manage to solve it? I'm running into the same issue...

**Comment by jiberan** [comment]
I would a reason - paths to js/css in basepage.html are relative.

Do not use http://host/cgi-bin/smokeping.cgi, just use http://host/smokeping

**Comment by Gregged** [comment]
I kept the old version 2.6.11-3 because of large network and it is stable BUT I just tried installing version 2.7.3 and I ran into the same problem. I tried your solution but it did not work. Do you know the component that allows the zoom for graphs?

**Comment by Gregged** [comment]
Issue resolved, I was doing incorrectly, using the solution giving by Jiberan i.e Do not use http://host/cgi-bin/smokeping.cgi, just use http://host/smokeping works like a charm
