### ISSUE TITLE
blank space when a lot of targets have packet loss

### ISSUE THREAD

**Issue by elieh94** [oetiker/SmokePing#135]
hello guys i have a problem when a lot of targets have packet loss all other targets will show same blank space but they don't have problem ,in the photos related to this message i have a continuous local ping but it's make a blank space as shown in the photo 
![local machine](https://user-images.githubusercontent.com/44481014/47527943-89a3fb80-d8ac-11e8-905c-4ebfd0c072a7.PNG) anyone can help me to solve this problem

**Comment by 4f96a64d** [comment]
Try reducing the timeouts for the probes, decrease the minimum interval (fping) or define multiple probes of the same type with different names and split them between your hosts.

**Comment by elieh94** [comment]
can't reduce my timeout i think i will change my statistic i made a change in the minimum interval i put it now 0.001

**Comment by Eideen** [comment]
Can you tell us about your setup?
