### ISSUE TITLE
Anyone managed to used smokeping to plot iperf results?

### ISSUE THREAD

**Issue by MrTiptop** [oetiker/SmokePing#141]
I am looking to measure upload and download speeds across WAN links between multiple offices, I looked at speedtest-cli, but this seems to only work for internet based servers (you cant point it to an internal server). I was wondering if you could use iperf to test speeds and then smokeping/RRDtools to plot? i am open to suggestions.

**Comment by MrTiptop** [comment]
Any news on this feature?

**Comment by oetiker** [comment]
Features normally get created by people who want them :) or by people paying someone to have the features created.

**Comment by MrTiptop** [comment]
:) fair enough

**Comment by Strykar** [comment]
@MrTiptop It's not that hard, most of the heavy lifting is already done for you. See this PGSQL probe for an example - https://github.com/Strykar/smokeping-plugins

**Comment by lbsou** [comment]
I would suggest using PerfSonar for this.

**Comment by dagelf** [comment]
Are there any Smokeping modules that monitor things other than latency? I suppose adding some does make sense as it could remove the need for other dashboards and monitoring tools. The codebase seems geared towards latency graphing, is it modular enough to easily add throughput graphs?

**Comment by lockywolf** [comment]
I am using AnotherCurl, with slightly tweaked regexps, to measure speed to the nearest Linux mirror.
A poor substitute for iperf3, but does let me understand when the network speed sucks.
