### ISSUE TITLE
Curl.pm shows response times for timeouts and other errors (and suggested fix)

### ISSUE THREAD

**Issue by heistp** [oetiker/SmokePing#142]
When curl has a connection timeout, it still prints the output line specified by the -w flag, so timeouts are reported as valid responses with response time around the length of time of the timeout. To fix this, I've been running locally with a change that only pushes the time if curl's exit status is 0, so that timeouts are reflected in "average loss":

```
331a332,333
> 		} else {
> 			push @times, $val if (defined $val and $expectOK);
333d334
< 		push @times, $val if (defined $val and $expectOK);
```

So I'd suggest this change, and possibly another probe parameter like `require_success` to disable it if there are cases where the response time is desired even when there's an error.

Thoughts? Shall I submit a pull request?

**Comment by oetiker** [comment]
yes please
