### ISSUE TITLE
Ajax image returns more than Content-Length

### ISSUE THREAD

**Issue by Gunni** [oetiker/SmokePing#144]
When a zoomed in image is requested [this block of code](https://github.com/oetiker/SmokePing/blob/3eb7434cecc23df3cb7dd23d1fc97a41d206102d/lib/Smokeping.pm#L1430) returns that to the client, but when it returns it will continue outputting html beyond the sent Content-Length.

We placed a `exit 0;` on [this line](https://github.com/oetiker/SmokePing/blob/3eb7434cecc23df3cb7dd23d1fc97a41d206102d/lib/Smokeping.pm#L1440) and it stopped happening, but i am unsure if that has any negatives.

We spotted this issue when our Citrix NetScaler was dropping the requests for zoomed in images.

Bug found by @Polarina.

**Comment by oetiker** [comment]
this has been fixed in 7d2260ec2a2d4eec2544555a54049bb9a10b2b58
