### ISSUE TITLE
smokeping and RRDcached

### ISSUE THREAD

**Issue by Eideen** [oetiker/SmokePing#148]
Hi
Have anyone made smokeping work with RRDcached?

**Comment by blakedot** [comment]
OpenBSD's port has a nice bit of doc on it:  
https://openports.pl/path/net/smokeping

**Comment by ronnyaa** [comment]
for people that are searching for this later... 

`Environment="RRDCACHED_ADDRESS=unix:/var/run/rrdcached.sock"`
into the smokeping.service systemd file fixed it on debian. 

I also changed rrdcached to run as smokeing and -b /var/lib/smokeping to avoid permissions and path issues for rrdcached

**Comment by NoifP** [comment]
More detail for Debian 13: [https://gist.github.com/NoifP/55f4ac2ca9aee78b84dffa5aadfea93b](https://gist.github.com/NoifP/55f4ac2ca9aee78b84dffa5aadfea93b)
