### ISSUE TITLE
Probes not sending errors to log when binary exits uncleanly

### ISSUE THREAD

**Issue by lelutin** [oetiker/SmokePing#151]
Hi there,

When trying to create a systemd unit for the debian package, I made a small mistake in the setup and the fping probe was not able to do anything.

the daemon was started with `ExecStart=/usr/sbin/smokeping --pid-dir=/run/smokeping`. Systemd catches messages from the daemon's startup but there was no output from probes about errors. the only way I could see what was happening was by strace'ing the FPing probe process. This makes it difficult to debug a failing probe.

Did I miss anything obvious that needs to be used or setup in order to get error output from probes?

**Comment by deajan** [comment]
Hi, you could modify your systemd unit file in order to add the following to [Service]
```
StandardOutput=syslog
StandardError=syslog
```

If you need a separate log, just add another line to it
```
SyslogIdentifier=smokeping
```

Then create the corresponding syslog entry in /etc/rsyslog.d/smokeping.conf
```
if $programname == 'smokeping' then /var/log/smokeping-daemon.log
if $programname == 'smokeping' then ~
```

Reload rsyslog and voilà :)

**Comment by lelutin** [comment]
Hi! thanks for the feedback.

the unit file already had `StandardError=syslog`, so I've added `StandardOutput=syslog`, but the result is the same. I can see log lines from the startup of smokeping daemon, but then I get no output from the fping probe.

I can see this after the service has started:

~~~
root@debian-9-amd64:~# journalctl -f -xu smokeping.service
-- Logs begin at Fri 2019-02-08 06:25:25 UTC. --
Feb 08 06:26:34 debian-9-amd64 systemd[1]: Starting Latency Logging and Graphing System...
-- Subject: Unit smokeping.service has begun start-up
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit smokeping.service has begun starting up.
Feb 08 06:26:35 debian-9-amd64 smokeping[4833]: Starting syslog logging
Feb 08 06:26:35 debian-9-amd64 smokeping[4833]: Note: logging to syslog as local0/info.
Feb 08 06:26:35 debian-9-amd64 smokeping[4833]: Daemonizing /usr/sbin/smokeping ...
Feb 08 06:26:35 debian-9-amd64 smokeping[4837]: Smokeping version 2.007003 successfully launched.
Feb 08 06:26:35 debian-9-amd64 smokeping[4837]: Not entering multiprocess mode for just a single probe.
Feb 08 06:26:35 debian-9-amd64 smokeping[4837]: FPing: probing 1 targets with step 300 s and offset 286 s.
Feb 08 06:26:35 debian-9-amd64 systemd[1]: Started Latency Logging and Graphing System.
-- Subject: Unit smokeping.service has finished start-up
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit smokeping.service has finished starting up.
-- 
-- The start-up result is done.
~~~

The FPing probe gets an error when trying to call the fping binary (because of some config error probably), but I don't see this error popping up in the logs

**Comment by lelutin** [comment]
the unit file currently looks like this:

~~~
root@debian-9-amd64:~# cat /lib/systemd/system/smokeping.service
[Unit]
Description=Latency Logging and Graphing System
Documentation=man:smokeping(1)
After=network.target

[Service]
ExecStartPre=/bin/mkdir -p /run/smokeping
ExecStart=/usr/sbin/smokeping --pid-dir=/run/smokeping
# If running service in master/slave setup, you might want to override
# ExecStart with something like the following:
#ExecStart=/usr/sbin/smokeping --master-url=http://127.0.0.1/smokeping.fcgi --cache-dir=/var/lib/smokeping --shared-secret=/etc/smokeping/smokeping_secrets --pid-dir=/run/smokeping
ExecReload=/bin/kill -HUP $MAINPID
StandardOutput=syslog
StandardError=syslog
Type=forking
PIDFile=/run/smokeping/smokeping.pid

[Install]
WantedBy=multi-user.target
~~~

**Comment by deajan** [comment]
I'm not really sure that the missing fping output is your problem here.
I had the fping issue with new protocol switches, so I first decided to launch smokeping manually, in order to get all stdout and stderr output. I indeed got some SMTP DSN complaints, but nothing about fping even if it didn't work because of the new -4 parameter.
So there's nothing more to catch by systemd IMO.

**Comment by lelutin** [comment]
@deajan right, the issue was that I was running the debian testing package on a stretch host (and so the fping version was too old) -- but that part I knew, I was just wondering why I wasn't getting log lines for this.

thanks for confirming that you also didn't get output from the probe.

then maybe there's something wrong with the probe that needs fixing? I'll have to compare what other probes are doing wrt logging.

**Comment by lelutin** [comment]
from what I can see, there are some places where each probe uses perl's "croak" to shout out about malformed input.

however -- and this is true for all probes -- there doesn't seem to be any error code checking after actually running the command associated with the probe. so in the example case of FPing and the missing `-4|-6` flags, we're not receiving any notice that the command failed to be called.

I think it would be nice to check out return code after execution with `open3` and use "die" if we get a non-zero code to show users that something went wrong

**Comment by lelutin** [comment]
I was able to get information about call errors for FPing's binary (e.g. when the binary exits with a non-zero return code) and the message gets grabbed by logs.

this patch howerver causes smokeping to exit entirely which I don't know if it's desirable. but for now at least calls to fping that error out don't pass under the radar.

my perl skills are extremely limited so please do advise about style errors or other concerns that this patch might bring to your mind:

~~~
--- /vagrant/smokeping-pkg/lib/Smokeping/probes/FPing.pm        2019-01-24 00:14:54.286350199 +0000
+++ /usr/share/perl5/Smokeping/probes/FPing.pm  2019-02-10 00:14:38.882714013 +0000
@@ -161,6 +161,8 @@
         map { $self->{rtts}{$_} = [@times] } @{$self->{addrlookup}{$ip}} ;
     }
     waitpid $pid,0;
+    my $rc = $?;
+    croak "@cmd returned with exit code $?. run with debug enabled to get more information" unless $? == 0;
     close $inh;
     close $outh;
     close $errh;
~~~

**Comment by lelutin** [comment]
@oetiker I'm wondering if the patch in the previous comment triggers some warnings in your eye. the goal of the patch is to get some sign in logs if a probe is erroring out. I'm wondering though if we'd like to use something different than "croak" in order to avoid exiting smokeping completely (e.g. maybe other probes are working correctly)

if this seems interesting to integrate, and once we reach some kind of consensus about what the patch should look like, I would apply it to all probes in order to catch similar issues elsewhere when a probe's binary is erroring out.

**Comment by oetiker** [comment]
the might work yes .to output @cmd I would use join(" ",@cmd) and and I would suggest to use 'carp' instead of croak and you have to make sure to 'use Carp' at the start of the module
