### ISSUE TITLE
smokeinfo errors out with message about locale

### ISSUE THREAD

**Issue by lelutin** [oetiker/SmokePing#154]
While trying to understand better another bug report about the same error message during build, I got the following while trying to call smokeinfo:

~~~
root@debian-9-amd64:/vagrant/smokeping-src# smokeinfo /etc/smokeping/config
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = "en_CA.utf8",
        LC_MEASUREMENT = "fr_CA.UTF-8",
        LC_PAPER = "fr_CA.UTF-8",
        LC_MONETARY = "fr_CA.UTF-8",
        LC_NUMERIC = "fr_CA.UTF-8",
        LC_TIME = "fr_CA.UTF-8",
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
Resetting LC_NUMERIC failed probably because your international setup of the LC_ALL to "en_CA.utf8" is overridding LC_NUMERIC.  Setting LC_ALL is not compatible with smokeping... at /usr/share/perl5/Smokeping.pm line 48.
Compilation failed in require at /usr/share/perl5/Smokeping/Info.pm line 6.
BEGIN failed--compilation aborted at /usr/share/perl5/Smokeping/Info.pm line 6.
Compilation failed in require at /usr/sbin/smokeinfo line 7.
BEGIN failed--compilation aborted at /usr/sbin/smokeinfo line 7.
~~~

When you set LC_ALL to a value of "C", the script is more happy and runs:

~~~
root@debian-9-amd64:/vagrant/smokeping-src# LC_ALL=C smokeinfo /etc/smokeping/config
-bash: warning: setlocale: LC_ALL: cannot change locale (en_CA.utf8)
# node_path;med_avg;med_min;med_max;med_now;loss_avg;loss_max;loss_now
/Local/LocalMachine;8.125000e-05;5.000000e-05;9.000000e-05;8.583333e-05;0.000000e+00;0.000000e+00;0.000000e+00
~~~

Since `smokeinfo` is intended to be called as a script on the command line, it would make sense for this script to clear out LC_ALL by itself in order to avoid locale issues.

**Comment by oetiker** [comment]
the error indicates that you have not properly installed en_CA.utf8 locales on your system ...

**Comment by lelutin** [comment]
@oetiker I've tried installing the locale en_CA.utf8 by running `dpkg-reconfigure locales` and chosing it in the list, and the error is still visible preventing the script to run without forcing LC_ALL to C

**Comment by oetiker** [comment]
the problem is that by forcing C locale people with properly configured systems will be rather unhappy to see perl losing its ability to deal with their chosen locale ...

**Comment by lelutin** [comment]
but the current situation is that smokeinfo does not run at all with locales configured with LC_ALL (which debian and derivatives do through the locales package).

the same happens with the main build of smokeping, Smokeping.pm when it tries to change a locale setting and seeing that LC_ALL is taking over. for this one, the debian package was setup to clear out LC_ALL so that the build succeeds.
