### ISSUE TITLE
cross references between man pages

### ISSUE THREAD

**Issue by lelutin** [oetiker/SmokePing#162]
Hi there,

Francesco Potortì <Potorti@isti.cnr.it> reported the following to the debian package in 2014, but it was never reported here because of a certain level of inactivity around the package.

See: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=740852

I would help out with a pull request but I frankly have no idea currently how perl's pod thing works.

Text from the original report:

~~~
The smokeping packages does a good job of providing man pages.
Unfortunately, those are not linked, so I found no way of knowing their
names other than using dlocate.

In many places a reference is made to other man pages, but without
mentioning their names.  Each man page misses at least REFERNCE section
where the other pages are listed.
~~~

I just looked at how other software do it, and they usually have a SEE ALSO section with a couple links to related man pages and sometimes URLs to further upstream documentation. For example the cups pages do this:

https://www.cups.org/doc/man-lpadmin.html#SEE_ALSO

cheers!

**Comment by oetiker** [comment]
sure ... PRs welcome as usual!

**Comment by lelutin** [comment]
ok! I looked up documentation and it seems like it's really easy to do. I'll send a PR today

**Comment by lelutin** [comment]
btw, it's a little unrelated to the original report, but I found out some pages were not being generated. In doc/Makefile.in there's something about using pod2man for

* lib/Somkeping.pm -> should go to section 3
* lib/Smokeping/RRDtools.pm -> should go to section 3

but neither of these end up being compiled for some reason. I don't quite understand yet what would be missing for these pages to get generated

**Comment by lelutin** [comment]
> btw, it's a little unrelated to the original report, but I found out some pages were not being generated. In doc/Makefile.in there's something about using pod2man for
> 
>     * lib/Somkeping.pm -> should go to section 3

ok never mind that comment.. I figured out that Smokeping.pm is used for generating the smokeping_config(5) page. The other file says that it's not specific to smokeping, so I guess one could look up documentation for the rrdtool binary instead?
