### ISSUE TITLE
100% loss in graph shown with color

### ISSUE THREAD

**Issue by OE5DRO** [oetiker/SmokePing#172]
how can i setup the graph to show a 100% loss (all packets) with a color, not just blank?
some did it like here  https://smokeping.aws.nate-online.com/smokeping/smokeping.cgi?target=Cox.Home here 20/20 packets. its not allowed with loss_colors setting.
and automatic setup only shows for example 19/20. if all packets lost there is only a emty space like in this issue https://github.com/oetiker/SmokePing/issues/135

pse help

**Comment by Strykar** [comment]
@OE5DRO By _loss_colors_ do you mean `loss_background` as set under `+detail` in `/etc/smokeping/config`?

> **[loss_background](https://oss.oetiker.ch/smokeping/doc/sm.html)** - Should the graphs be shown with a background showing loss data for emphasis (yes/no)?
> If this option is enabled, uptime data is no longer displayed in the graph background.

**Comment by meleschi** [comment]
I think what @OE5DRO is asking for is when the loss is 100%, to have a background color rather than white.  The loss_background just extends the color (when applicable) up and down the graph.  nodata_color only colors the graph when there is no smokeping data.  There is currently no way that I've seen to cause a color to appear on the graph when smokeping is running, but is experiencing 100% packet loss in it's test.

For example:

![Screenshot 2019-07-29 17 03 54](https://user-images.githubusercontent.com/3778607/62088592-0ccef500-b223-11e9-9d47-27db74ceaea1.png)

**Comment by oetiker** [comment]
try `nodata_color`

**Comment by meleschi** [comment]
@oetiker  - The above graph IS with nodata_color enabled.  nodata_color only colors the graph if the smokeping client has no data for that timeperiod, not if there was 100% packet loss during that time period.

**Comment by oetiker** [comment]
true

**Comment by dagelf** [comment]
Awesome! I see it's already been merged.

**Comment by dagelf** [comment]
Another note... it looks like the actual colors are stored in the RRD.... so if you update you will only get red backgrounds from the date of upgrade.

**Comment by dagelf** [comment]
So the source doesn't use tabs. This is great... it also colors your old graphs of course.

**Comment by alitvak69** [comment]
I tried copying new Smokeping.pm and commenting influx modules.  It made no difference for me. I blocked the ping on remote server and had an empty graph displayed.  Anything I am missing?

**Comment by timdonovanuk** [comment]
+1 to this. 

It doesn't make sense that "smokeping isn't running" and "total loss of connectivity" shows identically in graphs.

**Comment by Maltz42** [comment]
Bumping to keep this open.  A two-line change was posted above that would make this happen, though perhaps it should be a config option.  But the bar for this one seems pretty low.

**Comment by oetiker** [comment]
this is in 2.8.0 !

**Comment by timdonovanuk** [comment]
Could you provide maybe 1 sentence on it then? "It's enabled by default" or "you configure it via xyz" or even just link to the PR/code commit if you don't feel like documenting or discussing!

**Comment by timdonovanuk** [comment]
Thanks :)

**Comment by oetiker** [comment]
have a look at `nodata_color` ...

**Comment by Maltz42** [comment]
Fantastic.  Thanks again!

**Comment by timdonovanuk** [comment]
`nodata_color = FFB0B0`

`Error: line 58: color must be defined with in rrggbb syntax`

Am I doing something stupid here?

**Comment by oetiker** [comment]
hihi yes ... else it would say: RRGGBB

**Comment by Timi7007** [comment]
Is there an option to get the new behavior in the overview, not just ```+ detail```? Also it doesn't seem to be enabled by default, I had to add ```loss_background```. Maybe I'm missing something?

**Comment by xairrick** [comment]
> Is there an option to get the new behavior in the overview, not just `+ detail`? Also it doesn't seem to be enabled by default, I had to add `loss_background`. Maybe I'm missing something?

I also had to add ```loss_background = yes``` to get it to show up

**Comment by luckman212** [comment]
Can someone, anyone please TL;DR how to get this red loss background enabled on a stock setup? I'm running 2.8.2 as a Docker container from https://hub.docker.com/r/linuxserver/smokeping 🙏

**Comment by NaterGator** [comment]
That's an interesting observation, my experience is "time in the future" and pending (ie: in flight) probes do not color as loss, but maybe something has changed since I last updated my instance... I'll let others chime in with their experience.

**Comment by xairrick** [comment]
I have 2.8.2 and don't have the issue of uncharted territory showing as red.  @luckman212 what time ranges are you using?
![image](https://github.com/user-attachments/assets/422db66a-297c-4af1-822e-3ff3cbc96feb)

**Comment by luckman212** [comment]
@xairrick What are your values for `loss_background` and `nodata_color`?

**Comment by xairrick** [comment]
> @xairrick What are your values for `loss_background` and `nodata_color`?

`loss_background = yes`
I'm not setting `nodata_color` and it's working as expected when there packet loss
![image](https://github.com/user-attachments/assets/aa88c220-845e-4718-9e05-6aa343e2605d)

**Comment by Loughty** [comment]
This config works on "+ detail", but it gives an error when you try to use it in "+ overview"

`ERROR: /etc/smokeping/config.d/Presentation, line 42: unknown variable 'loss_background'`

@Timi7007 also mentioned that, way back in the 2022, it looks like nobody cared
> Is there an option to get the new behavior in the overview, not just + detail? Also it doesn't seem to be enabled by default, I had to add loss_background. Maybe I'm missing something?

That's weird, packet loss in your connection should be important to everyone, but for some reason the default behavior is to hide it, instead of highlighting it, and in the case of overview, you can't even change that behavior

If there is a workaround, please let me know, I'm using the version 2.8.2 installed from the Ubuntu 26 repository, thank you in advance, and sorry for the inconvenience

**Comment by luckman212** [comment]
Not sure, this ancient project really is "as is" not getting much maintenance. But I will say that 2.9.0 is the current version so you should try to install that and re-test.
