### ISSUE TITLE
Generate Graph URL Issues

### ISSUE THREAD

**Issue by dekenberg** [oetiker/SmokePing#173]
When I was following up on the fix for #5, I found an error with the URL when generating graph.  When you type in the time range and generate, I would expect the URL to update to show the new start and end which it currently does not. This is a problem if you wish to share a specific graph via url. The graph it displays is correct and for individual usage it isn't a large problem but if the page resets (either through the autorefresh or a browser refresh) the generated graph is lost and replaced with the original graph with the parameters in the URL. 

This is right after generating a graph:
![image](https://user-images.githubusercontent.com/15372614/56367605-35266c80-61bb-11e9-80f8-2fef90a6d9a1.png)

This is a few minutes after generating that graph (Autorefresh triggered):
![image](https://user-images.githubusercontent.com/15372614/56367986-24c2c180-61bc-11e9-86de-934d98e53294.png)

Is this the intended behavior? If not, where would you recommend a change occur for a patch to fix this?

**Comment by Strykar** [comment]
Yep, looks like that fix just disables autorefresh when zooming the image.

@oetiker Should the URL even be changed for a full page refresh here?

**Comment by oetiker** [comment]
ideally the url with be changed when the user 'zooms' the graph

**Comment by dekenberg** [comment]
It would be nice for sharing graphs if 'zooming' the image via the cropper changed the url. @oetiker Should generating a graph also change the url? I saw on the demo site when generating the graph the url doesn't change - this makes it more of a process to share a graph generated over a time from via the gui. For example if I generated a graph with start time of 2019-04-22 12:03 and an end time of 2019-04-23 5:03 the correct graph is rendered. Currently in the demo the url has start=2019-04-25%2012:03 and end=now. Should the url in this case change to have start=2019-04-22%12:03 and end=2019-04-23%5:03?

![image](https://user-images.githubusercontent.com/15372614/56821303-85cd4380-6813-11e9-8dcf-36ff74c976dd.png)

**Comment by oetiker** [comment]
how about integrating https://github.com/oetiker/RrdGraphJS example is here https://tobi.oetiker.ch/smokenav/

**Comment by dekenberg** [comment]
Would you accept a patch that would update the url with the time range values when the Generate! button is pressed?

**Comment by oetiker** [comment]
sure

**Comment by rborgmaster** [comment]
I would :-)

**Comment by dekenberg** [comment]
I made the rewrite happen on the javascript side before the post action happens.

**Comment by dekenberg** [comment]
Patch has been merged - on generate the url should change. This will deal with any autorefresh problems with a generated graph as well.
