### ISSUE TITLE
AnotherDNS  ipversion = 6 does not function.

### ISSUE THREAD

**Issue by meleschi** [oetiker/SmokePing#178]
I've configure AnotherDNS to use IPv6, however it continues to use IPv4.

My config is as follows:

++ AWSv6AnotherDNS

menu=AWSv6-AnotherDNS
title=AWSv6-AnotherDNS
probe=AnotherDNS
ipversion=6

+++ dns1-nic-aws
menu=dns1.nic.aws
title=dns1.nic.aws
host=dns1.nic.aws

My PerlFu is weak, so I cannot deduce where / how ipversion os sourced and then sent to the AnotherDNS module.   Please let me know if any other information is needed from me to help troubleshoot this.

**Comment by Strykar** [comment]
@meleschi Post relevant, snipped `smokeping --debug` log.
I will try to reproduce this later in the week.

**Comment by meleschi** [comment]
Please note I'm using a remote smokeping slave to run AnotherDNS.

I've started a slave with --debug and grepped for the relevant AnotherDNS log lines.  They are outputted here:

[root@server log]# cat smokeping.log  | grep -i AnotherDNS  |grep dns1.nic.aws
Tue Jun 25 04:08:20 2019 - AnotherDNS: dns1.nic.aws: got 1.0288300000e-01 1.0288800000e-01 1.0289000000e-01 1.0290600000e-01 1.0291400000e-01 1.0293500000e-01 1.0294900000e-01 1.0297000000e-01 1.0297300000e-01 1.0297400000e-01 1.0297900000e-01 1.0298700000e-01 1.0302700000e-01 1.0302800000e-01 1.0304000000e-01 1.0304300000e-01 1.0306400000e-01 1.0307500000e-01 1.0308500000e-01 1.0312600000e-01
Tue Jun 25 04:09:00 2019 - AnotherDNS: dns1.nic.aws: got 1.0297900000e-01 1.0298700000e-01 1.0300800000e-01 1.0306100000e-01 1.0306900000e-01 1.0307000000e-01 1.0307100000e-01 1.0307800000e-01 1.0308000000e-01 1.0310200000e-01 1.0310400000e-01 1.0311000000e-01 1.0311000000e-01 1.0311400000e-01 1.0313400000e-01 1.0313600000e-01 1.0314900000e-01 1.0318300000e-01 1.0322600000e-01 1.0348300000e-01

I have two AnotherDNS menu items for dns1.nic.aws, one is configured with NO ipversion and is reporting back with IPv4 results.  The other is configured as defined in the initial issue with ipversion=6, but still reporting back ipv4 results (i.e., not DNS polling an IPv6 address).  I've validated that with tcpdump looking for DNS traffic to the IPv6 address for dns1.nic.aws.

Nowhere in the log files on the slaves do I see ipversion=6 being output in the logs for AnotherDNS.  If you tell me something more specific to look for in the log file I can pull it out and paste it here for analysis.

Could this be happening because I am using a different smokeping version on my slaves?

Tue Jun 25 04:06:48 2019 - Smokeping version 2.006010 successfully launched.

**Comment by meleschi** [comment]
My Main smokeping server is running:

Tue Jun 25 10:04:32 2019 - Smokeping version 2.007003 successfully launched.

All my slaves are running:

Tue Jun 25 04:06:48 2019 - Smokeping version 2.006010 successfully launched.

**Comment by Strykar** [comment]
@meleschi Still no --debug output.

**Comment by meleschi** [comment]
I've updated the slaves to the latest smokeping version, and I now see IPv6 DNS traffic.  I'll close this ticket.  Thank you for your assistance and for writing so much great software.
