### ISSUE TITLE
Thoughts on adding favicon to basepage.html.dist?

### ISSUE THREAD

**Issue by Strykar** [oetiker/SmokePing#186]
@oetiker Could we bundle `<link REL="icon" HREF="./favicon.png" TYPE="image/png"/>` to `basepage.html.dist` using `favicon.png` found at https://oss.oetiker.ch/smokeping/favicon.png

This would add `1KB` to a Smokeping install.

**Comment by rezzorix** [comment]
Just for anyone who might look for a solution; if you edit the basepage.html, you could also add a  base64 encoded favicon.

Means you wouldnt need to add a file anywhere, just the following code into the head-section:

`<link href="data:image/x-icon;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH1gQSFA8qQC+y8wAAAB10RVh0Q29tbWVudABDcmVhdGVkIHdpdGggVGhlIEdJTVDvZCVuAAABd0lEQVQoz5WSy07CQBSGTzuF6Y1buQSiCYSgYli7MC54AZc+gC/CE7kzrPQBjDsNIdF4I8oCwr1gO51OOy4aAbGS+K/OTM6X85/5R2g0GvAfSesHjPyj3LyasrIKxch3fXHiSN0Fvv4wbCZuAobsnld7Scw4wIhEhiSCEc/IbgqzZicTMuG0NEpi9jhRLzuZOUXBJRK4ITOfr1yIy6oYIwDQ7KSX3QDgcWFgR9ZtrwCLIQAoJ8j2pVG9Xg8qDsJe0j5MWcW4g5FvMUQ8cRvQXeAplXY0mlfpftI+zpu1tBURed/CHhdCAADoWfiml3gxlYUraZKXVdxKwq6lPx8mqvM97QcQaEalV1O57cffTGVXdzKKa8isNdI3l/6tzly+eM4BQDlOQl4pVEECLDSHUowUNCqsdedVelYZAEB7rIUkfVKYHaQs4okTIjEuJKJePMoCY1fvRghwN9R9gIJKs4orCtxm6Gmq3I/01lDnob+1PdbWR/+lL5mtm+fskIeBAAAAAElFTkSuQmCC" rel="icon" type="image/x-icon" />`

You can basically convert any icon into base64; e.g. here https://base64.guru/converter/encode/image/ico

**Comment by oetiker** [comment]
nice, can you please make a PR?

**Comment by rezzorix** [comment]
> nice, can you please make a PR?

https://github.com/oetiker/SmokePing/pull/316
I hope its ok to also add another small QOL-Tweak... (Home-Link)
