### ISSUE TITLE
slave not get new config 

### ISSUE THREAD

**Issue by Crazy-Geng** [oetiker/SmokePing#193]
first, when i changed Targets in master  , then smokeping --reload.  but, slave not get new config

so ,  how to handle it ?

**Comment by Strykar** [comment]
Read https://github.com/oetiker/SmokePing/wiki/FAQ#master-slave-setups

**Comment by jossvw** [comment]
Hi

Thank you for all the feedback

It is working

Kind regards

Joss van Wyk

**Comment by Strykar** [comment]
@oetiker Perhaps this could be closed?

**Comment by jossvw** [comment]
yes
