### ISSUE TITLE
DNS Probe - resolve multiple domains again different NameServers

### ISSUE THREAD

**Issue by MrTiptop** [oetiker/SmokePing#194]
Hello, is there a way to configure the DNS probe to resolve (dig) multiple domains again multiple name servers? Currently i can only find documentation to configure a single domain to resolve again different nameservers/dns servers.

Thanks

**Comment by svenvg93** [comment]
Not sure if you still need an answer on this one :)

Maybe not the best solution but adding a second probe could work.

in the probe file

```
+ DNS
binary = /usr/bin/dig
lookup = google.com
pings = 5
step = 300

+ DNS2
binary = /usr/bin/dig
lookup = bbc.co.uk
pings = 5
step = 300
```

in the target file;

```
+ DNSProbes
menu = DNS Probes
title = DNS Probes

++ GoogleDNS
menu = Google DNS
title = Google DNS 8.8.8.8
host = 8.8.8.8
probe = DNS

++ GoogleDNS1
menu = Google DNS2
title = Google DNS 8.8.8.8
host = 8.8.8.8
probe = DNS2
```

Then you can combine them in a multi graph.

**Comment by pfworks** [comment]
You can also do this in the target file (and can probably add the lookup to each entry but haven't tried.
`+ DNS2Probes
menu = DNS2 Probes
title = DNS2 Probes
probe = DNS
lookup = bbc.co.uk

++ GoogleDNS2
menu = GoogleDNS2
title = Google DNS 8.8.8.8
host = 8.8.8.8
`
