### ISSUE TITLE
ExpLoss contains wrong description

### ISSUE THREAD

**Issue by dfroehl** [oetiker/SmokePing#197]
In matchers/ExpLoss.pm line 18 the module description contains a mistake in the example to call the matcher.

`pattern =  CheckLoss`
is obviously wrong for this matcher and should be replaced with
`pattern = ExpLoss`

It is a rather simple fix but documentation on
https://oss.oetiker.ch/smokeping/matcher/ExpLoss.en.html
is currently missleading when using this matcher.

**Comment by oetiker** [comment]
would you like to do a PR ?

https://github.com/oetiker/SmokePing/edit/master/lib/Smokeping/matchers/ExpLoss.pm

**Comment by dfroehl** [comment]
Done.
https://github.com/oetiker/SmokePing/pull/198
