### ISSUE TITLE
curl task does NOT push data into rrd

### ISSUE THREAD

**Issue by askdaddy** [oetiker/SmokePing#20]
i already have the data in log:
Wed May 28 11:06:25 2014 - Curl: curl output: 'Time: 0.082 DNS time: 0.000 Redirect time: 0.000', result: 0.082
Wed May 28 11:06:25 2014 - Curl: curl output: 'Time: 0.092 DNS time: 0.000 Redirect time: 0.000', result: 0.092
Wed May 28 11:06:25 2014 - Curl: curl output: 'Time: 0.070 DNS time: 0.000 Redirect time: 0.000', result: 0.07
Wed May 28 11:06:26 2014 - Curl: curl output: 'Time: 0.072 DNS time: 0.000 Redirect time: 0.000', result: 0.072
Wed May 28 11:06:26 2014 - Curl: curl output: 'Time: 0.085 DNS time: 0.000 Redirect time: 0.000', result: 0.085
Wed May 28 11:06:26 2014 - Curl: curl output: 'Time: 0.083 DNS time: 0.000 Redirect time: 0.000', result: 0.083

but when i fetch the rrd,it shows me :
1401239520: -nan -nan -nan -nan -nan -nan -nan -nan
1401240240: -nan -nan -nan -nan -nan -nan -nan -nan
1401240960: -nan -nan -nan -nan -nan -nan -nan -nan
1401241680: -nan -nan -nan -nan -nan -nan -nan -nan
1401242400: -nan -nan -nan -nan -nan -nan -nan -nan
1401243120: -nan -nan -nan -nan -nan -nan -nan -nan
1401243840: -nan -nan -nan -nan -nan -nan -nan -nan
1401244560: -nan -nan -nan -nan -nan -nan -nan -nan
1401245280: -nan -nan -nan -nan -nan -nan -nan -nan
1401246000: -nan -nan -nan -nan -nan -nan -nan -nan
1401246720: -nan -nan -nan -nan -nan -nan -nan -nan

**Comment by askdaddy** [comment]
fixed

**Comment by KalyanKB** [comment]
can you provide the resolution for the same...
