### ISSUE TITLE
Feature request - Add option to alias hostnames under graphs

### ISSUE THREAD

**Issue by Strykar** [oetiker/SmokePing#200]
@oetiker When using multihost graphs with hosts that exceed 20 characters in their hostname, the actual data below the image is cluttered and not easy to read at a glance.
The appearance is worse with slave multigraph results as the slave name is appended.

Here is an example multi-graphing popular public DNS with just a 3 character slave name (`i-5`):
![DNS_smokeping](https://user-images.githubusercontent.com/2946372/66141357-2cb6d680-e621-11e9-9319-00eb183f6029.png)
Repeating the slave name for each target seems like an oversight? It might be better placed in the title - `Last 3 Hours from i-5`

Using IPs instead of hostnames in the config might appear to fix the issue.
However, IPs aren't intuitive to quickly review several multihost graphs.

Would it be possible to use hostnames in the config but allow aliases for those targets in graphs/multigraphs so they could be arranged legibly?

**Comment by oetiker** [comment]
sure, go ahead ... pull requests are always appreciated ...
