### ISSUE TITLE
target data in sql db would be amazing...

### ISSUE THREAD

**Issue by syadnom** [oetiker/SmokePing#202]
The config file is a real pain to maintain.  Would really love to see host/target data in a mysql database.

**Comment by oetiker** [comment]
I agree. PRs are welcome!

**Comment by masonke** [comment]
A data base would be nice to have, but in the meantime, found a way to make life easier. You may already be doing this, so my apologies if you are.

We broke our monolithic Targets file into a series of sub-files, each containing one top level grouping. These are called using @include directives in the Targets file.

 By breaking it up into a series of files, it makes editing easier. and reduces the time to find an error. Plus, we can give an app team their own Targets file to maintain, reducing the workload on the admins.


We keep all the files in a Git repo to make change control simpler and catch errors.

**Comment by mad-ady** [comment]
I have a perl script that builds the config and generates the necessary files. It's ugly, but gets the data from the database.

**Comment by masonke** [comment]
That sounds pretty interesting. Would you mind sharing the script?

**Comment by mad-ady** [comment]
@masonke Here is the script: http://paste.ubuntu.com/p/M2J9FKJMG3/
It´s ugly and custom made for my needs. But you may get the picture on how you can build something that suites your needs...
It is run via cron whenever I need to change the smokeping configuration (it overwrites the existing config)

**Comment by masonke** [comment]
Thanks, it sure beats starting from scratch!

Kevin
