### ISSUE TITLE
Mailhost Clarification

### ISSUE THREAD

**Issue by dekenberg** [oetiker/SmokePing#206]
I have been having trouble getting email alerts triggering via the mailhost variable. I have found this in the documentation 

mailhost
Instead of using sendmail, you can specify the name of an smtp server and use perl's Net::SMTP module to send mail (for alerts and DYNAMIC client script). Several comma separated mailhosts can be specified. SmokePing will try one after the other if one does not answer for 5 seconds.

But in the Perl_Modules I do not see NET::SMTP added. Does it need to be added or is the documentation out of date?

**Comment by oetiker** [comment]
it should get added if you want to use this feature

**Comment by dekenberg** [comment]
Thanks for the Clarification
