### ISSUE TITLE
Installing with homebrew

### ISSUE THREAD

**Issue by fotoflo** [oetiker/SmokePing#212]
Hello,
I would like to run smokeping on my mac, but i dont see a package for it on home brew. There is a package on apt apparently - https://www.linuxcloudvps.com/blog/install-smokeping-on-ubuntu-16-04/

Any suggestions on how to run it on mac?

**Comment by joshlewis** [comment]
I wish this would be re-opened and investigated. I would like to run it on my Mac as well, @fotoflo. Did you ever find any way to make it happen?
