### ISSUE TITLE
Add traceroute function (like ovh)

### ISSUE THREAD

**Issue by zdzichu6969** [oetiker/SmokePing#213]
Hi
Please add traceroute option like smokeping in ovh ( http://smokeping.ovh.net/smokeping?target=EMEA.AS29562 )

https://i.imgur.com/WhYQO4o.png

:)

**Comment by dedimark** [comment]
yes, please.

**Comment by paunadeu** [comment]
It's currently handled by https://github.com/mattdees/traceping

**Comment by deajan** [comment]
Got a 2020 working copy here https://github.com/deajan/traceping

Don't expect this to be improved a lot more though.

**Comment by dagelf** [comment]
The OVH implementation looks pretty useless, as it's not storing history... and it's probably not storing it efficiently either. 

To implement what they have, I would simply add a "custom command" option that can be run during each ping, and the output kept for display. With optional number of history lines. Which will get bloated of course. 

 I would rather focus on writing a separate traceroute history tool that stores traceroutes efficiently, that can be integrated with Smokeping and other tools...

**Comment by deajan** [comment]
Since my last comment, I've worked on a full blown implementation of traceroute history, which can be included in smokeping, and which stores history, makes diff and decides to send alerts based on RTT changes.

You can find the project at https://github.com/deajan/tracehoute_history
Thrilled to get reviews.

**Comment by dagelf** [comment]
Can you post a new link for the traceroute history project? I'm keen to
take a look.

**Comment by deajan** [comment]
Hmm... I've posted the link above already, see https://github.com/deajan/traceroute_history

**Comment by ocentelles** [comment]
https://github.com/everywan-dev/smokeping
