### ISSUE TITLE
Smokeping not graphing

### ISSUE THREAD

**Issue by Ilikectrl** [oetiker/SmokePing#218]
version: 2.7.2
question:
I install smokeping-2.7.2 on my virtual machine.After my abnormal shutdown my host ,there are no image in smokeping.
This is error massge:
ERROR: Could not save png to '/opt/smokeping/htdocs/cache/OUT_mini.png'
how can I do ?

**Comment by Strykar** [comment]
Start here and share your troubleshooting results - https://github.com/oetiker/SmokePing/wiki
