### ISSUE TITLE
WARNING Master said 501 Protocol scheme 'https' is not supported (LWP::Protocol::https not installed)

### ISSUE THREAD

**Issue by deajan** [oetiker/SmokePing#223]
Hello,

I use to run a couple of smokeping instances with slaves.
Today I've tried to run a smokeping slave v2.7.3 current git that connect to the same version as master, using https (with apache).
When I try to run the slave, I get:
```
WARNING Master said 501 Protocol scheme 'https' is not supported (LWP::Protocol::https not installed)
```

Having installed missing `perl-LWP-Protocol-https` package and restarted the master (also installed later on the slave), I get the same message.

Is slave contacting master via https supported by Smokeping ?
If yes, anything I did wrong ?
Of course, I can reach the master via https.

Best regards.

**Comment by oijkn** [comment]
Hi, I have the same problem and solved partially by installing `p5-Crypt-SSLeay` package.

Now I have another message error : 
`WARNING Master said 500 Can't connect to master-smokeping.fr:443 (Crypt-SSLeay can't verify hostnames)`

**Comment by oetiker** [comment]
perl ssl support is getting more and more secure ... if your website does not have a propper ssl certificate things can get a bit hard

**Comment by oijkn** [comment]
> 
> 
> perl ssl support is getting more and more secure ... if your website does not have a propper ssl certificate things can get a bit hard

Hi @oetiker,

I tried to disable the SSL verification and set manually my proxy, but the slave can't connect to master.

```
    my $ua = LWP::UserAgent->new(
        agent => 'smokeping-slave/1.0',
        timeout => 60,
        ssl_opts => { verify_hostname => 0 });
        #env_proxy => 1 );

    $ua->proxy('https', 'http://my.proxy:80/');
```

Any advice to get it working, please ?

**Comment by deajan** [comment]
@oijkn Thanks, but it seems that the Crypt-SSLeay code is quite old and has been obsoleted by Net-SSLeay  (see https://bugzilla.redhat.com/show_bug.cgi?id=1744782).
I managed to install it using cpan `cpan install Crypt-SSLeay` on a CentOS 8 box anyways.

As for the SSL problem, I used some google-fu (I don't speak perl) since now I don't have any weird perl dependancy issues anymore.
You need to totally disable SSL verification for your agent.
Here's my solution that I just put into production:
`
    my $ua = LWP::UserAgent->new(
        agent => 'smokeping-slave/1.0',
        timeout => 60,
        env_proxy => 1 );
    $ua->ssl_opts(verify_hostname => 0,
              SSL_verify_mode => 0x00);
`

**Comment by oijkn** [comment]
@deajan I'm trying your code but that doesn't work, I'm still getting error :

WARNING Master said 500 Can't connect to master-smokeping.fr:443 (Operation timed out)

**Comment by deajan** [comment]
@oijkn At least you may outrule a direct SSL certificate problem (I can confirm this code works on my Smokeping 2.7.3 slave).
"Operation timed out" looks more like a network problem.
Have you tried accessing your master from slave via curl to outrule any network config / proxy problem ?
```
curl -k https://my.smokeping.master/smokeping.fcgi
curl -k --proxy http://whateveryourproxyis https://my.smokeping.master/smokeping.fcgi
```

Does that work ?
Also, [this ](https://stackoverflow.com/a/17787133/2635443) stackoverflow seems to bring some light.
Please report back if you find a solution.

**Comment by oijkn** [comment]
@deajan Trying curl command from the slave work good.
Now all work like a charm by adding these lines :
```
    my $ua = LWP::UserAgent->new(
        agent => 'smokeping-slave/1.0',
        timeout => 60,
        ssl_opts => {verify_hostname => 0, SSL_verify_mode => 0x00},
        proxy => [[ 'http', 'https' ] => 'http://my.proxy.server:80/'],
        env_proxy => 1 );
```

Thank you very much for your help and for pointing me in the right direction 👍

**Comment by deajan** [comment]
@oijkn Thanks for reporting back. Hope this thread will help others later.
