### ISSUE TITLE
Working with self-signed certificates/pki in master-slave setup

### ISSUE THREAD

**Issue by dagobertdocker** [oetiker/SmokePing#227]
I want to use smokeping master-slave with TLS and a custom pki (i.e. self-signed ca). However, smokeping does not support this at the moment, it seems.

I can of course set `PERL_LWP_SSL_VERIFY_HOSTNAME=0`. However, this completely disables any validation and makes one open to a man in the middle attack. So, this is a very bad option.

Then one could feed either the correct CA to validate against to LWP

```perl
my $ua = LWP::UserAgent->new;
$ua->ssl_opts(SSL_ca_file => 'theRootCA.pem');
$ua->get('https://xxx');
```

...or include a hash of the correct certificate the https server presents

```perl
my $ua = LWP::UserAgent->new;
$ua->ssl_opts(SSL_fingerprint => 'sha1$XXX')
$ua->get('https://xxx');
```
References: [stackoverflow.com](https://stackoverflow.com/a/47668190), [zonalivre.org](https://zonalivre.org/2013/07/04/ignore-ssl-certificates-in-lwp/)

But that means code change, and the binary is managed by (i.e. replaced by) the package manager on a modern Linux distro...

Could someone please make this configurable in a sane way?

**Comment by deajan** [comment]
Does PERL use the truststore that comes with the system ?
If so, wht don't add the your self signed cert to the truststore ?
