### ISSUE TITLE
Smokeping 2.6.9 fails to build on FreeBSD

### ISSUE THREAD

**Issue by jeroenh** [oetiker/SmokePing#23]
Smokeping 2.6.9 is the latest version in the FreeBSD ports tree, and it currently fails to build with an error:

```
smokeping_config.pod around line 81: alternative text 'the master/slave mode' contains non-escaped | or /
```

I believe this is because of `lib/Smokeping.pm:2634`:

```
L<the master/slave mode|smokeping_master_slave>.
```

The "/" character there has to be escaped.

**Comment by lelutin** [comment]
@oetiker if I understand this issue correctly, this has been fixed for a while now since there's been releases after 2.6.9, am I correct?

**Comment by oetiker** [comment]
true ... lets close and see if someone complains :)
