### ISSUE TITLE
Update default Database config to save more data

### ISSUE THREAD

**Issue by saaly182** [oetiker/SmokePing#230]
The default *** Database *** config only keeps 3.5 days of full data, 180 days of 1h data, and 360 days of 12h data. The amount of storage needed for that is small in modern terms.

By contrast, the following retention on requires about 10MB:
100 days of full data
400 days of 1h aggregation data
1200 days of 12h aggregation data

Given that it's common to want to relook at data from a while ago, and that disk capacity has gone way up, consider updating config.dist.in to have retentions like above.

**Comment by oetiker** [comment]
I agree ... can you provide a PR ?

**Comment by saaly182** [comment]
Will do.
