### ISSUE TITLE
fping6: can't specify both -4 and -6

### ISSUE THREAD

**Issue by timdream** [oetiker/SmokePing#233]
I've just upgraded from Ubuntu 16.04 to 20.04, and I realized all the FPing6 probe is down.

Upon some searching I found [this blog post](https://blog.andersen.nu/2019/08/01/smokeping-and-fping6-probe) saying that `fping6` can no longer accept `fping6 -6 <address>`

```
# fping6 -6 ipv6.google.com
fping6: can't specify both -4 and -6
```

I can verify this is the case for me, and update my local config fix the issue

```diff
  + FPing6
- binary = /usr/bin/fping6
+ binary = /usr/bin/fping
```

Also, according to `zcat /usr/share/doc/fping/NEWS.Debian.gz`

```
fping (4.0-4) unstable; urgency=medium

  For backward compatibility with remote smokeping configurations on older
  releases, the fping Debian package will continue to provide
  /usr/bin/fping6 until at least Debian 9 Stretch is end of life.

  Please do not use fping6 in scripts or configurations which don't
  require it for backwards-compatibility with older fping versions.

 -- Axel Beckert <abe@debian.org>  Wed, 06 Sep 2017 01:57:56 +0200

fping (4.0-3) unstable; urgency=medium

  From the upstream changelog:

    fping and fping6 are now unified into one binary. It means that, for
    example, doing 'fping google.com' is going to ping the IPv6 IP of
    google.com on IPv6-enabled hosts.

  You can force usage of IPv6 or IPv4 by adding the commandline options
  -4 or -6.

 -- Axel Beckert <abe@debian.org>  Sat, 26 Aug 2017 09:26:46 +0200
```

Is this a Debian bug or a fping bug? Should the example binary path in `FPing6.pm` be modified accordingly?

**Comment by timdream** [comment]
I realized this is a fping bug fixed by upstream:

https://github.com/schweikert/fping/commit/6fd4f8bd91abc43f80078bdd0084cb6d2b1de7f1

I am keeping this issue open to see if you would like to update the example.

**Comment by timdream** [comment]
Or, other than fixing the example path, do something similar to 8f44e977f2683cc4fd804516d245639fa73cc1c7 and don't specify `-6` if the binary path is already `fping6`?

**Comment by timdream** [comment]
Keep open please

**Comment by ZaphodB** [comment]
jFYI
I ran into the same issue on Debian stable and just fixed it by pinning the fping package from testing.
```
# cat /etc/apt/preferences.d/limit-testing 
Package: *
Pin: release a=testing
Pin-Priority: 200

# cat /etc/apt/preferences.d/fping-testing 
Package: fping
Pin: release a=testing
Pin-Priority: 600
```
