### ISSUE TITLE
Feature Request: Webhooks

### ISSUE THREAD

**Issue by cb3inco** [oetiker/SmokePing#235]
I'd love to see webhooks (Slack, Rocket.Chat, etc.) be integrated.

**Comment by agail** [comment]
@cb3inco incoming or outgoing?
Outgoing is fairly easy, just hook up your script to:

```
*** Alerts ***
to = |/full_path_to_script/slack_notify.sh

```
Have a peek at https://github.com/tomwillfixit/smokeping/blob/master/slack_notify.sh for inspiration.
