### ISSUE TITLE
Custom Alert

### ISSUE THREAD

**Issue by leostereo** [oetiker/SmokePing#237]
Hi guys ,
Is it possible to process alert triggers ?
My idea is to get an alert to my telegram app instead to my email.
Is that possible ?
Is it possible to log an alert ?
Regards.

**Comment by agail** [comment]
Sure, check out https://bfy.tw/Ozc4

```
*** Alerts ***
to = |/full_path_to_script/slack_notify.sh
from = leostereo@yourmail.com 
```
Have a look at https://github.com/tomwillfixit/smokeping/blob/master/slack_notify.sh for fetching relevant alert data.

Good luck!

**Comment by leostereo** [comment]
Hello ...
Thanks for your advice.
I did something similar to test:
at config file:

+someloss
type = loss
# in percent
#pattern = >0%,*12*,>0%,*12*,>0%
#comment = loss 3 times  in a row
pattern = >1%
to = |/opt/smokeping/smoke_alert_handler.pl
comment = any loss

+rttdetect
type = rtt
# in milliseconds
pattern = >50
to = |/opt/smokeping/smoke_alert_handler.pl
comment = routing messed up again ?

Then, in my smoke_alert_handler.pl , I have:
[root@smokeping smokeping]# cat /opt/smokeping/smoke_alert_handler.pl
#!/bin/perl
my ($name_of_alert,$target,$loss_pattern,$rtt_pattern,$hostname) = @ARGV;
`/bin/logger $hostname $target $name_of_alert`;
`curl "
https://api.telegram.org/bot830790814:AAF9J6sL7EEc8XESmZX2EH6NMjjBM1V1v_4/sendMessage?chat_id=856661113&text=$hostname
$target $name_of_alert"`;

For some reason this is not working.
I already did: chmox +x smoke_alert_handler.pl.

Any idea to debug this ?
Regards.
Leandro.



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by agail** [comment]
Add a line to you perl script that write/appends the output data to a file, /tmp/alert.log
Then you'll know if the script triggers properly. If not, there's where you'll start investigating.
I'd change the shebang to #!/usr/bin/env perl

**Comment by leostereo** [comment]
> Add a line to you perl script that write/appends the output data to a file, /tmp/alert.log
> Then you'll know if the script triggers properly. If not, there's where you'll start investigating.
> I'd change the shebang to #!/usr/bin/env perl

I was loggin lines.
anyway , it is working now ... there was missing the line alers=xxx, xxx .
Thanks.

**Comment by josefelipeduarte** [comment]
Look that [Telegram Smokeping](https://github.com/josefelipeduarte/Smokeping-alerts)
