### ISSUE TITLE
basic custom alert test

### ISSUE THREAD

**Issue by leostereo** [oetiker/SmokePing#245]
Hi guys ... im trying to get my custom alert working:
I wrote a very basic rules and script just to make it work:

```
+someloss
type = loss
pattern = >1%
to = |/opt/smokeping/alert_notify.sh
comment = any loss

+rttdetect
type = rtt
pattern = >1
to = |/opt/smokeping/alert_notify.sh
comment = routing messed up again ?
```
The script:
```
[root@smokeping smokeping]# cat alert_notify.sh
#!/bin/bash
alertname=$1
target=$2
losspattern=$3
rtt=$4
hostname=$5
echo "$(date) $1 $2 $3 $4 $5" >> /opt/smokeping/alert_smokeping.log
```

This is not working ... any idea ?
Regards.

**Comment by leostereo** [comment]
It is working now.
After adding the alert line to tarjet host , it began generating alerts.
So , doing:

```
++++ sa-east-1_1
menu = sa-east-1_1
probe = OpenSSHMikrotikRouterOSPing
title = sa-east-1_1 - 52.67.255.254
ssh_port = 22000
host = 52.67.255.254
source = 10.16.1.1
rtable = bgp_x_silica
alerts = someloss,rttdetect
```
Question is ... do i need to set this line on every tarjet ?
How can I declare in a global scope to get all my tarjets reporting alerts ?
Regards.

**Comment by leostereo** [comment]
ok ... this looks like a crazy chat .. i ask and answer at same time.
But ... yes ... it is possible.
You can add the alerts line under each section , for example:

```
++ ROOT_SERVERS
menu = ROOT_SERVERS
title = ROOT_SERVERS
alerts = someloss,rttdetect
@include /opt/smokeping/etc/config.d/CORE_ROOT_SERVERS
```
Regards.

**Comment by jpdsceu** [comment]
> Hi guys ... im trying to get my custom alert working:
> I wrote a very basic rules and script just to make it work:
> 
> ```
> +someloss
> type = loss
> pattern = >1%
> to = |/opt/smokeping/alert_notify.sh
> comment = any loss
> 
> +rttdetect
> type = rtt
> pattern = >1
> to = |/opt/smokeping/alert_notify.sh
> comment = routing messed up again ?
> ```
> 
> The script:
> 
> ```
> [root@smokeping smokeping]# cat alert_notify.sh
> #!/bin/bash
> alertname=$1
> target=$2
> losspattern=$3
> rtt=$4
> hostname=$5
> echo "$(date) $1 $2 $3 $4 $5" >> /opt/smokeping/alert_smokeping.log
> ```
> 
> This is not working ... any idea ?
> Regards.

Hi Leo,

On the Alerts file. What do you have under:
*** Alerts ***
to = 
from = 

These are 2 mandatory fields.
