### ISSUE TITLE
What do the CURL graphs actually show ?

### ISSUE THREAD

**Issue by alex-leonhardt** [oetiker/SmokePing#25]
Hi,

not an issue - more a general question - when using CURL to graph a URL, what does it actually show me as they seem to be the same as for PING - so I'm assuming "connect" time ? 

Alex

**Comment by mad-ady** [comment]
It measures page load time (depeding on how you configure it) - the time it takes for curl to download the page you pointed it to, minus the time it took to resolve the server name via DNS.

**Comment by alex-leonhardt** [comment]
Thanks!
