### ISSUE TITLE
time for a new relase?

### ISSUE THREAD

**Issue by lelutin** [oetiker/SmokePing#265]
Hello,

The last release of Smokeping happened just a little bit more than two years ago on december 20th 2018. Since there's been a couple fixes merged in to master since then, do you think it makes sense to produce a new release?

**Comment by O2Graphics** [comment]
Hello,
I agree, a new release would be welcome! :-)
The current version (2.7.3) have this bug: https://github.com/oetiker/SmokePing/issues/183 and every package maintainer have to add this patch to fix it: https://github.com/oetiker/SmokePing/commit/e9004e8bbeb30d33778afaf70a5f8b95ff38d6ba

I recently hit this bug on FreeBSD: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=253161 so we added the patch: https://www.freshports.org/commit.php?category=net-mgmt&port=smokeping&files=yes&message_id=202102020814.1128E63N095428@repo.freebsd.org

Similarly, there is this bug report on Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=934170 and is fixed here: https://salsa.debian.org/debian/smokeping/-/commit/82cf41226910f690d8cc44c23238cc8c7f30e371

And, probably every other *BSD or Linux have this bug or patch in their packages.

**Comment by oetiker** [comment]
@O2Graphics if you could create PRs for these we can add them ... and then I'll be glad todo a release

**Comment by O2Graphics** [comment]
Hello @oetiker!

Thanks for your answer, but I don't understand what I should add in a PR? What I meant in my previous message is that we just need a new release, the patch fixing a specific bug is already in SmokePing's repo: https://github.com/oetiker/SmokePing/commit/e9004e8bbeb30d33778afaf70a5f8b95ff38d6ba :-)

**Comment by oetiker** [comment]
ah :) sorry did not check out the bugreports ... I thought you ran into other problems :)

**Comment by O2Graphics** [comment]
Haha, no, no other problem ;-)

PS: thanks for SmokePing, I've been using this great tool for the past 14 or 15 years!

**Comment by deveshmanish** [comment]
Not an official release but use if you want.

https://github.com/deveshmanish/SmokePing/releases/tag/v2.7.4

**Comment by svenvg93** [comment]
+1 for a new release so we can enjoy all new improvements and bugfixed :)

**Comment by oetiker** [comment]
done #289
