### ISSUE TITLE
Slaves ignoring step value

### ISSUE THREAD

**Issue by deveshmanish** [oetiker/SmokePing#270]
I have a master slave setup but the slaves are ignoring the step count defined in probes, concurrentprobes is set to yes. But the slaves are polling very aggressively even multiple times in a second which is causing rrd graphs error as minimum step count is 1sec but data is being sent multiple times in a second.

**Comment by deveshmanish** [comment]
![image](https://user-images.githubusercontent.com/4588019/117533590-472a1080-b00b-11eb-8548-83cea5ba33b7.png)

![image](https://user-images.githubusercontent.com/4588019/117533611-5f9a2b00-b00b-11eb-984a-4603bc016dc7.png)

![image](https://user-images.githubusercontent.com/4588019/117533643-7fc9ea00-b00b-11eb-8d3b-ce1f1476557f.png)

**Comment by Strykar** [comment]
Did you change step after the RRDs were created? Try deleting the existing RRDs and restart the master and slave.

**Comment by deveshmanish** [comment]
This is on a fresh install, interestingly enough if I change the concurrentprobes to no everything seems to work as normal but as expected I loose the ability to set probe specific step.

**Comment by deveshmanish** [comment]
Just to give a little bit more info the master slave have been setup on docker environment with alpine as the base.

**Comment by deveshmanish** [comment]
> This is on a fresh install, interestingly enough if I change the concurrentprobes to no everything seems to work as normal but as expected I loose the ability to set probe specific step.

Correction on the above, even if concurrentprobes is set to no the default step value fetched from database is also not being followed by the slaves.  The rrd errors are not occurring as the probes are being executed serially and total execution time is exceeding 1 minute.
![image](https://user-images.githubusercontent.com/4588019/117622674-83d34480-b190-11eb-9e4c-e39a08bedf85.png)

**Comment by deveshmanish** [comment]
Well the problem seems to have resolved after building latest version from source and making a few changes to Slave.pm and Master.pm.
