### ISSUE TITLE
empty graph if smokeping not run as root user.

### ISSUE THREAD

**Issue by likecreep** [oetiker/SmokePing#282]
Hi, I'm using ubuntu and using caddy as web server. And I used `apt install smokeping` to install smokeping.

Now I must run caddy and smokeping as root user to get the updated graph. But if I changed to run smokeping as `user smokeping` and run caddy as `user caddy`, the graph would not generate new datas and the graph would become empty.

also I hava `fcgiwrap`  run as `user www-data  ` 

So I have to manually run ` chmod -R 777 /var/lib/smokeping/` everytime after I adding a new target. 

Is there a way to not let them run as `root user` works together and without manually run ` chmod -R 777 /var/lib/smokeping/`?

**Comment by Strykar** [comment]
Smokeping writes the data, the web server user needs to be able to read this data, this is addressed in the FAQ - https://github.com/oetiker/SmokePing/wiki/FAQ  You need to fix ownerships and permissions.

https://wiki.archlinux.org/title/Smokeping#Caddy_2 has examples for Caddy.

**Comment by likecreep** [comment]
> Smokeping writes the data, the web server user needs to be able to read this data, this is addressed in the FAQ - https://github.com/oetiker/SmokePing/wiki/FAQ You need to fix ownerships and permissions.
> 
> https://wiki.archlinux.org/title/Smokeping#Caddy_2 has examples for Caddy.

thx

**Comment by Strykar** [comment]
@likecreep YW, there's even a script on the wiki - https://github.com/oetiker/SmokePing/wiki/Script-to-check-smokeping-webserver-ACLs
