### ISSUE TITLE
FPing interface param regex too restrictive

### ISSUE THREAD

**Issue by HendrikF** [oetiker/SmokePing#283]
It's nice that this feature got added in #234, but the regular expression is way too restrictive.
An example off the top of my head is `eth0.123`. https://github.com/oetiker/SmokePing/blob/f11bd10e0ff7542c266a172399deafd11fac1ff3/lib/Smokeping/probes/FPing.pm#L272

According to iproute2 only slashes, spaces, and nullbytes are forbidden and there is a maximum length:
https://git.kernel.org/pub/scm/network/iproute2/iproute2.git/tree/lib/utils.c?id=1f420318bda3cc62156e89e1b56d60cc744b48ad#n827
That restriction should probably be removed entirely.

**Comment by oetiker** [comment]
thanks for investigating ... can you please do a PR ?

**Comment by HendrikF** [comment]
See #284. I actually found another problem with the FPing probe that this fixes too.
