### ISSUE TITLE
Hard dependency on InfluxDB - should be loaded on demand

### ISSUE THREAD

**Issue by HendrikF** [oetiker/SmokePing#285]
I think it was a bad decision to unconditionally include InfluxDB modules in Smokeping. It's a hard dependency even for people not using it.

https://github.com/oetiker/SmokePing/blob/64633f41dae8b0326948a273c0b569c35a029a48/lib/Smokeping.pm#L26-L27

It even seems that it was optional while being developed. Optional: https://github.com/oetiker/SmokePing/pull/257/commits/45ec481e5d85cf5d08ccd620a063ef0edec37f77 Mandatory: https://github.com/oetiker/SmokePing/pull/257/commits/c4076fcdf9d3ca722df5dbe121bd1a77fac621c7

As this is my first time working with Perl, this is what I found about loading modules on demand: https://stackoverflow.com/a/251786

```perl
my $rc = eval
{
  require Term::ReadKey;
  Term::ReadKey->import();
  1;
};

if($rc)
{
  # Term::ReadKey loaded and imported successfully
  ...
}
```

Although it seems to be recommended to use [Try::Tiny](https://metacpan.org/pod/Try::Tiny).

**Comment by oetiker** [comment]
Indeed that is a bit of a big module for mandatory inclusion ... I agree ... would you care to provide a patch ?
I would suggest to 'require and import' if cfg->{InfluxDB} exists ... 

note that the 45ec481 was not actually optional since it used 'use'.

**Comment by HendrikF** [comment]
Oh, right, I missed that. It is even the main point of that SO answer.

**Comment by HendrikF** [comment]
See https://github.com/oetiker/SmokePing/pull/286

**Comment by HendrikF** [comment]
Merged, closing now.
