### ISSUE TITLE
Smokeping crashes when ran under sudo

### ISSUE THREAD

**Issue by kvz** [oetiker/SmokePing#29]
After installing smokeping from apt on ubuntu 12.04, I tried to run it (being root) like so:

``` bash
sudo -HEu smokeping env PATH="${PATH}" \
  LC_ALL=C \
  smokeping \
    --debug \
    --static=/var/www/html/smokeping \
    --config=/etc/smokeping/config
```

This went fine, until I tried it from cron.

After getting to the cronjob's STDERR, I found this error:

```
require Smokeping::probes::FPing failed: Can't locate IPC/Open3.pm:   Permission denied at /usr/share/perl5/Smokeping/probes/FPing.pm line 19, <File> line 3.
BEGIN failed--compilation aborted at /usr/share/perl5/Smokeping/probes/FPing.pm line 19, <File> line 3.
Compilation failed in require at (eval 22) line 2, <File> line 3.
```

It turned out that because my `PWD` was still `/root` FPing had some pathfinding troubles.

Changing the current directory to something owned by the `smokeping` user before running the sudo command, fixed my problem.

While maybe not directly a Smokeping issue, pathfinding from the script's directory (vs the user executing), or a more helpful error message might go a long way into a smoother onboarding process.

**Comment by ericpulvino** [comment]
I just hit this message and fixed it via the steps above... Thanks!

**Comment by weyou** [comment]
Wierd issue, thanks for the workaround
