### ISSUE TITLE
Unable to install Smokeping 2.8.2 on RedHat 8

### ISSUE THREAD

**Issue by AliArfan** [oetiker/SmokePing#297]
``Hi!

I tried to subscribe to the mailing-list but got no token back, so trying my luck here.   We have been running smokeping 2.7.3 for a while now, and the installation went trough without any problems on Redhat 8.  The  installation files were directly downloaded from: https://oss.oetiker.ch/smokeping/pub/

It should be noted that this VM is running in a closed environment with NO internet access. 

With that regards I have a two questions: 

1. Is it possible to keep the rdd files or just do a update of the existing 2.7.3 installation or do we have to install  it from scratch. 
2.  I tried to install the update on the same server, but I get the following error after running configuring and running make install:

``` gmake[1]: Entering directory '/opt/smokeping-2.8.2/thirdparty'
echo "** Installing Dependencies using Carton install"
** Installing Dependencies using Carton install
test -f cpanfile-5.26.snapshot && cp cpanfile-5.26.snapshot ../cpanfile.snapshot || true
test -x carton/bin/carton || PERL_CPANM_OPT= PERL_CPANM_HOME=/opt/smokeping-2.8.2/thirdparty PERL_CARTON_PATH=/opt/smokeping-2.8.2/thirdparty /bin/perl bin/cpanm -q --notest --local-lib-contained /opt/smokeping-2.8.2/thirdparty/carton Carton
! Couldn't find module or a distribution Carton
gmake[1]: *** [Makefile:431: cpanfile-5.26.snapshot] Error 1
gmake[1]: Leaving directory '/opt/smokeping-2.8.2/thirdparty'
gmake: *** [Makefile:359: install-recursive] Error
```

Any help will be appreciated

Thank you in advance!

**Comment by stingray78** [comment]
I'm having the same issue.

[]$ cd smokeping-2.8.2
[smokeping-2.8.2]$ sudo make
Making all in lib
make[1]: Entering directory `/home/local/STL-MO/adm-rmiller/smokeping-2.8.2/lib'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/home/local/STL-MO/adm-rmiller/smokeping-2.8.2/lib'
Making all in thirdparty
make[1]: Entering directory `/home/local/STL-MO/adm-rmiller/smokeping-2.8.2/thirdparty'
echo "** Installing Dependencies using Carton install"
** Installing Dependencies using Carton install
test -f cpanfile-5.16.snapshot && cp cpanfile-5.16.snapshot ../cpanfile.snapshot || true
test -x carton/bin/carton || PERL_CPANM_OPT= PERL_CPANM_HOME=/home/local/STL-MO/adm-rmiller/smokeping-2.8.2/thirdparty PERL_CARTON_PATH=/home/local/STL-MO/adm-rmiller/smokeping-2.8.2/thirdparty /bin/perl bin/cpanm -q --notest --local-lib-contained /home/local/STL-MO/adm-rmiller/smokeping-2.8.2/thirdparty/carton Carton
PERL_CPANM_OPT= PERL_CPANM_HOME=/home/local/STL-MO/adm-rmiller/smokeping-2.8.2/thirdparty PERL_CARTON_PATH=/home/local/STL-MO/adm-rmiller/smokeping-2.8.2/thirdparty PERL5LIB=/home/local/STL-MO/adm-rmiller/smokeping-2.8.2/thirdparty/carton/lib/perl5 /bin/perl /home/local/STL-MO/adm-rmiller/smokeping-2.8.2/thirdparty/carton/bin/carton install
Installing modules using /home/local/STL-MO/adm-rmiller/smokeping-2.8.2/cpanfile

gunzip failed: input file '/home/local/STL-MO/adm-rmiller/smokeping-2.8.2/thirdparty/sources/http%cpan.metacpan.org/02packages.details.txt.gz' does not exist
 at /home/local/STL-MO/adm-rmiller/smokeping-2.8.2/thirdparty/carton/lib/perl5/Menlo/CLI/Compat.pm line 442.
Installing modules failed


I have install Carton manually as well as all of the dependancies in cpanfile.  Nothing I can do to make it complete make.
