### ISSUE TITLE
OpenSSHJunOSPing.pm Enhancement (TOS)

### ISSUE THREAD

**Issue by don-robbery** [oetiker/SmokePing#30]
OpenSSHJunOSPing.pm currently does not support setting the tos bit in the ping command.  Having the ability to test class-of-service would be a great enhancement to smokeping.

Having the capability to set this as a per host override would be great that way we can have multiple graphs per host each one for a different class-of-service

Any chance you can implement this?

junos command is 'ping x.x.x.x tos Y'
where Y is the type of service between 0 and 7

**Comment by oetiker** [comment]
added in 9afefe1
