### ISSUE TITLE
All slave node data does not participate in chart sorting

### ISSUE THREAD

**Issue by yuqi33** [oetiker/SmokePing#300]
Hello everyone! 
  I deployed a set of smokeping servers in the master-slave mode to monitor the network, and found that because the web front-end is running on the master node, the monitoring results are not accurate, so the "nomasterpoll = yes" parameter is used to disable the master node to monitor data , Only use the slave node monitoring results to draw the graph. This creates a new problem, there is no topn data under the charts, prompting "No targets returned by the sorter". I don’t know if there is a problem with the configuration, or the program design In this way, the monitoring results of all slave nodes are not involved in the topn sorting. And the summary data under targets seems to only use the master node detection data to draw the graph, which leads me to use "nomasterpoll = yes" and there is no data on the summary graph.But after entering the specific branch, the monitoring data of the slave node can be displayed normally.The smokeping version is the latest 2.8.2,The configuration of the Presentation, Targets part is as follows, please help to see if there is any problem, ,thank you! 

```
*** Presentation ***

template = /etc/smokeping/basepage.html
charset  = utf-8

+ charts

menu = TOP
title = 各指标最大值统计

++ stddev
sorter = StdDev(entries=>10)
title = 最大标准差
menu = 标准差TOP10
format = Standard Deviation %f

++ max
sorter = Max(entries=>10)
title = 最大时延
menu = 最大时延TOP10
format = Max Roundtrip Time %f seconds

++ loss
sorter = Loss(entries=>10)
title = 最大丢包率
menu = 丢包率TOP10
format = Packets Lost %f

++ median
sorter = Median(entries=>10)
title = 最大中位数时延
menu = 时延中位数TOP10
format = Median RTT %f seconds

+ overview

width = 800
height = 120
range = 4h

+ detail

width = 800
height = 120
unison_tolerance = 2

"Last 4 Hours"    4h
"Last 24 Hours"   24h
"Last 3 Days"     3d
"Last 7 Days"     7d
"Last 30 Days"    30d
"Last 360 Days"   360d

#+ hierarchies
#++ owner
#title = Host Owner
#++ location
#title = Location
#++loss_colors
# Loss Color   Legend
# 1    00ff00    "<1"
# 3    0000ff    "<3"
# 1000 ff0000    ">=3"
#+multihost

++uptime_colors
 # Uptime      Color     Legend
 3600          00ff00   "<1h"
 86400         0000ff   "<1d"
 604800        ff0000   "<1w"
 1000000000000 ffff00   ">1w"

+multihost

*** Targets ***

probe = FPing

+cs
menu = 传输
title = 传输节点
slaves = BJ SH WH GZ CD
nomasterpoll = yes
host = /cs/bjcs/bjcs3 /cs/shcs/shcs2 /cs/whcs/whcs3 /cs/gzcs/gzcs3 /cs/cdcs/cdcs3 

++ bjcs
menu = 北京传输
title = 北京传输节点

+++ bjcs3
menu = 北京传输服务器
title = 北京传输服务器
host = 10.199.1.3

++ shcs
menu = 上海传输
title = 上海传输节点

+++ shcs2
menu = 上海传输服务器
title = 上海传输服务器
host = 10.199.2.10

++ whcs
menu = 武汉传输
title = 武汉传输节点

+++ whcs3
menu = 武汉传输服务器
title = 武汉传输服务器
host = 10.199.4.3

++ gzcs
menu = 广州传输
title = 广州传输节点

+++ gzcs3
menu = 广州传输服务器
title = 广州传输服务器
host = 10.199.3.3

++ cdcs
menu = 成都传输
title = 成都传输节点

+++ cdcs3
menu = 成都传输服务器
title = 成都传输服务器
host = 10.199.5.3

++ ty8
menu = 日本传输
title = 日本传输节点

+++ tycs1
menu = 日本CE58
title = 日本CE58
host = 172.16.2.3
```

各位,大家好!
  我使用主从模式部署了一组smokeping服务器用来监控网络,发现因为主机上运行有web前端,监测出来的结果不太准确,所以使用了nomasterpoll = yes参数禁用了所有节点的主机监控,只使用slave节点监测结果来绘制图形.由此产生了一个新的问题,charts下没有topn数据,提示"No targets returned by the sorter".不知道是否哪里的配置有问题,还是程序设计本就如此,所有slave节点的监测结果都没有参与到topn排序.并且在targets下的汇总数据似乎也是只采用主节点检测数据来绘制图形,导致我使用nomasterpoll = yes以后汇总图形上没有数据,但是进入具体分支以后slave节点的监测数据都能正常显示出来.Smokeping版本为最新的2.8.2,Presentation,Targets部分配置如下,请帮忙看下是否哪里有问题,谢谢!

<img width="1671" alt="1" src="https://user-images.githubusercontent.com/35123605/139584499-d8989b62-816e-4aa6-ab36-657781ce6eb9.png">
<img width="1672" alt="2" src="https://user-images.githubusercontent.com/35123605/139584498-57789865-55bc-4bdc-b5b0-f5367a3cf3b4.png">
<img width="1676" alt="3" src="https://user-images.githubusercontent.com/35123605/139584495-962e6747-427b-410a-9d02-32843a118d31.png">
<img width="1180" alt="4" src="https://user-images.githubusercontent.com/35123605/139584493-74770d3e-4cec-4ec9-8eef-6fa504fe6503.png">
<img width="1189" alt="5" src="https://user-images.githubusercontent.com/35123605/139584491-e3812c63-c831-497f-8b93-1e59a923430f.png">
<img width="909" alt="6" src="https://user-images.githubusercontent.com/35123605/139584654-2bfdd337-8bc7-43bc-8fef-51317ac6f580.png">

**Comment by 2ZZ** [comment]
Unstale - this is still an issue.
