### ISSUE TITLE
502 error when get an not exist rrd file.

### ISSUE THREAD

**Issue by ggfvictor** [oetiker/SmokePing#305]
Smokeping runs well for some month,but yesterday,it always show 502 error,I try to traceback but not found,then i debug for nginx error log that i found that
FastCGI sent in stderr: "[Thu Jun 20 01:16:59 2019] smokeping_cgi [client 66.249.79.179]: ERROR: slave 'dmit' is not defined in the '*** Slaves ***' section!" while reading response header from upstream, client: 66.249.79.179, server: myserver.com, request: "GET /?displaymode=n;start=2019-05-07%2004:30;end=now;target=america.us.level3sanjonse~dmit HTTP/1.1", upstream: "fastcgi://127.0.0.1:9007", host: "myserver.com"
that means the Google bot access a not exist page,then the server return 502 error and must be restarted by manually.
Why not 404 error but 502 error?
How can i avoid this error? because when an illegal user access the not exist page that means the whole master service will be halt on.

**Comment by Ranofult** [comment]
same problem

`172.68.253.24 - - [08/Jan/2022:01:34:07 +0800] "GET /cache/mainland/HK-AP/cm-gz-120232~HK-AP_last_2592000.png HTTP/2.0" 200 22391 "https://***/?target=mainland.HK-AP.cm-gz-120232" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15"
172.68.253.24 - - [08/Jan/2022:01:34:07 +0800] "GET /cache/mainland/HK-AP/cm-gz-120232~HK-AP_last_604800.png HTTP/2.0" 200 26432 "https://***/?target=mainland.HK-AP.cm-gz-120232" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15"
108.162.246.99 - - [08/Jan/2022:01:34:57 +0800] "GET /?target=globe HTTP/2.0" 500 272 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)"
172.68.253.24 - - [08/Jan/2022:01:35:08 +0800] "GET /?target=mainland.HK-AP.cm-gz-120232 HTTP/2.0" 502 150 "https://***/?target=mainland.HK-AP.cm-gz-120232" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15"
172.68.253.24 - - [08/Jan/2022:01:35:10 +0800] "GET /?target=mainland.HK-AP.cm-gz-120232 HTTP/2.0" 502 150 "https://***/?target=mainland.HK-AP.cm-gz-120232" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15"`
