### ISSUE TITLE
Add to FAQ - Smokeping 2.8.2 compile on Ubuntu 20.04 depends on zlib1g-dev

### ISSUE THREAD

**Issue by agail** [oetiker/SmokePing#318]
Fresh install of Ubuntu 20.04.3 (+gcc make rrdtool librrds-perl libssl-dev)

```
! Configure failed for Net-SSLeay-1.92. See /usr/local/src/smokeping-2.8.2/thirdparty/work/xxxxx.xxxx/build.log for details.
! Installing the dependencies failed: Module 'Net::SSLeay' is not installed
! Bailing out the installation for IO-Socket-SSL-2.074.
```

After some investigation, we need to install  package **zlib1g-dev** as well in order to sucessfully compile from source.

_Hopefully it might save some time for other poor souls ..._

**Comment by oetiker** [comment]
hi @agail, cool ... just go edit the wiki page! https://github.com/oetiker/SmokePing/wiki/FAQ/_edit
