### ISSUE TITLE
Add support for responsive images

### ISSUE THREAD

**Issue by HinataKato** [oetiker/SmokePing#322]
When you viewing on cell phones or similar aspect ratios, you need to swipe the page, and responsive images can solve the problem

**Comment by HinataKato** [comment]
> This issue has become stale and will be closed automatically within 7 days. Comment on the issue to keep it alive.

🫠

**Comment by Strykar** [comment]
@HinataKato Have you considered sharing a PR adding the feature?

**Comment by HinataKato** [comment]
> @HinataKato Have you considered sharing a PR adding the feature?

I wish I could, but I am not good at frontend (coding actual), but I will try my best🥲

**Comment by HinataKato** [comment]
#349
