### ISSUE TITLE
Question: Why do I need to reload apache2 (fcgid enabled) in order to see menu items in smokeping?

### ISSUE THREAD

**Issue by agail** [oetiker/SmokePing#323]
This is not a smokeping question per se, but I hope someone could shine a little light on this.

To me it feels something to do with fcgid, but I could  be wrong. Looked at the configuration options for fcgid but couldn't find anything related to my issue. 

Adding a menu entry should be visible instantaneous as I save the config. However, this doesn't happen until I reload apache2.
*Surly, this can't be the way it supposed to work, right?*
 
For instance, this doesn't occur if I run nginx with fcgiwrap, then the menu item display as soon as I save.

*smokeping.home.arpa.conf*
```
<VirtualHost *:80>
    DocumentRoot "/opt/smokeping/htdocs"
    ServerName smokeping.home.arpa

    ErrorLog ${APACHE_LOG_DIR}/smokeping_error.log
    CustomLog ${APACHE_LOG_DIR}/smokeping_access.log combined
 
    RedirectMatch 301 ^/$ /smokeping.fcgi

    ScriptAlias /smokeping.fcgi /opt/smokeping/htdocs/smokeping.fcgi
    Alias /cache /opt/smokeping/cache

     <Directory "/opt/smokeping/htdocs">
        Options +ExecCGI +FollowSymLinks
        AllowOverride Options
        Require all granted
     </Directory>

     <Directory "/opt/smokeping/cache">
        Require all granted
     </Directory>
    </VirtualHost>
```

*fcgid.conf (untouched)*
```
<IfModule mod_fcgid.c>
  FcgidConnectTimeout 20

  <IfModule mod_mime.c>
    AddHandler fcgid-script .fcgi
  </IfModule>
</IfModule>
```

*Smokeping relevant config paths*
```
*** General ***
[snip]
imgcache = /opt/smokeping/cache
imgurl   = cache
datadir  = /opt/smokeping/data
piddir  = /opt/smokeping/var
cgiurl   = http://smokeping.home.arpa/smokeping.fcgi
[snip]

````

Setup
Ubuntu 20.04.4 LTS
Smokeping compiled from src

**Comment by lelutin** [comment]
Hi there,

Maybe what's happening is just that as long as the apache process is running, it keeps the perl code loaded and running?

e.g. this part seems to imply that as long as there's stuff coming in the script keeps replying to requests:

https://github.com/oetiker/SmokePing/blob/master/bin/smokeping_cgi#L23-L25

And this configuration option seems to imply that processes are kept around for a certain time before being discarded:

https://httpd.apache.org/mod_fcgid/mod/mod_fcgid.html#fcgididletimeout

**Comment by agail** [comment]
Thanks for the feedback @lelutin 

> https://httpd.apache.org/mod_fcgid/mod/mod_fcgid.html#fcgididletimeout
Lowered the value to 20 along with FcgidIdleScanInterval to 20, did nothing for me.

Do you run apache2 with fcgid and (forgive me for being bold) what does your config look like?

**Comment by lelutin** [comment]
> > https://httpd.apache.org/mod_fcgid/mod/mod_fcgid.html#fcgididletimeout
> 
> Lowered the value to 20 along with FcgidIdleScanInterval to 20, did nothing for me.

oh, it's too bad that it didn't help :\

> Do you run apache2 with fcgid and (forgive me for being bold) what does your config look like?

I don't, I use the debian package's default configuration with mod_cgi which tends to run the perl cgi in the same process as the apache worker
