### ISSUE TITLE
lists.oetiker.ch doesn't answer to subscribe

### ISSUE THREAD

**Issue by meepmeep** [oetiker/SmokePing#327]
I have some question about the graphs on smokeping (the way loss are represented between your demo site and mine).
I tried to subscribe this morning to the mailing list @lists.oetiker.ch, but I never received the cookie to validate it.

Is it still active ?

**Comment by oetiker** [comment]
no the mailinglist has been retired ... use the discussions function ... https://github.com/oetiker/SmokePing/discussions
