### ISSUE TITLE
SmokePing Mesh Feature

### ISSUE THREAD

**Issue by cnighswonger** [oetiker/SmokePing#333]
Such a feature would permit multiple master and/or slave SmokePings to share common target data.

This arose out of the discussion here: #331

**Comment by cnighswonger** [comment]
How difficult would this be to implement?

Could the slave code be co-opted to do this?

**Comment by oetiker** [comment]
The way the slaves currently work, is that they connect to the central server, and get their instructions from there, do the work and report back ... in a mesh setup, multiple masters would have to be called, the requests merged, and the results then distributed accordingly.

If you have time and skill or monney, this is certainly a feasible project :)
