### ISSUE TITLE
Fix for bug #90 was incomplete

### ISSUE THREAD

**Issue by dadv** [oetiker/SmokePing#341]
Hi!

The bug #90 was fixed 5 years ago for FPing.pm with commit:
https://github.com/oetiker/SmokePing/commit/72ed1570fbb4ae0b90846625e1a3bd5d2bade531

Same bug is still present in FPingContinuous.pm and same change solves same problem there. Please fix FPingContinuous.pm, too.

**Comment by dadv** [comment]
As side note: modern curl binary does not print all needed info if called just as "curl --help", so Curl.pm and AnotherCurl.pm fail to detect "-m" and "--interface" options support even if it is present. Modern curl prints it all only if called as "curl --help all".

**Comment by Strykar** [comment]
> As side note: modern curl binary does not print all needed info if called just as "curl --help", so Curl.pm and AnotherCurl.pm fail to detect "-m" and "--interface" options support even if it is present. Modern curl prints it all only if called as "curl --help all".

Please open a separate issue for Curl/AnotherCurl.pm.

**Comment by Strykar** [comment]
> Hi!
> 
> The bug #90 was fixed 5 years ago for FPing.pm with commit: [72ed157](https://github.com/oetiker/SmokePing/commit/72ed1570fbb4ae0b90846625e1a3bd5d2bade531)
> 
> Same bug is still present in FPingContinuous.pm and same change solves same problem there. Please fix FPingContinuous.pm, too.

Please test with https://github.com/Strykar/SmokePing/blob/master/lib/Smokeping/probes/FPingContinuous.pm and let us know if it works.

**Comment by dadv** [comment]
It works, thanks.
