### ISSUE TITLE
Update deb repro ?

### ISSUE THREAD

**Issue by svenvg93** [oetiker/SmokePing#355]
Not this is the correct location to ask, sorry if not. 

When installing with the default Debian repro's, version 2.7.x will be installed. Would it be possible to update that version also to 2.8.x. Or how can it be done.

**Comment by svenvg93** [comment]
:)

**Comment by iustin** [comment]
You would have to file a bug against Debian for them to update the package. Yes, it looks like even in unstable, only 2.7.3 is available - the maintainer seems a bit behind.

**Comment by iustin** [comment]
And I forgot to ping the Debian bug, so it looks like this release will have old smokeping.

For the record, the Debian bug is https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1004308.
