### ISSUE TITLE
HiDPI monitors and image formats

### ISSUE THREAD

**Issue by iustin** [oetiker/SmokePing#357]
Hi,

I only am running 2.7.3 since Debian's packaging seems a bit behind (there's a separate issue on that), so maybe this was already fixed in newer versions, but a quick look at the CHANGES file suggests not (the responsive image code is about a different issue).

On HiDPI screens, the PNG graphs as drawn by rrd are, as expected, "blurry". There is a very old thread about it [on the mailing list](https://lists.oetiker.ch/pipermail/smokeping-users/2017-April/005955.html) which talks about rrd's zoom option, or doubling the size of the graphs, but all of this works only for a specific client size. A better fix seems to move away from PNG to something like SVG, which results in "native" HiDPI support.

I did a quick and dirty test, and the changes seem to be minimal - replace the image format and content-type in `Graphs.pm` and main `Smokeping.pm`, and all works. A proper patch would mean having this as a configurable option, but before going that way, would you be interested at all in such a patch?

From my point of view:

- PNG images are smaller (about 4× I think), but SVG compresses better over the wire (a plain gzip results in 6-7x), so it's neutral overall
- SVG might be marginally slower to render, but it works well on both normal DPI and HiDPI screens
- if configurable and defaulting (for a while, at least) to PNG, should have no impact on existing installations

Thoughts?

**Comment by iustin** [comment]
Friendly ping, would you be open to a pull request implemeting this?

**Comment by iustin** [comment]
Pinging to keep it open.

**Comment by Strykar** [comment]
@iustin PRs would be welcome, please do.

**Comment by iustin** [comment]
Years later, and only now managed to send a pull request, sorry.
