### ISSUE TITLE
influxdb  Error inserting measurement into influxdb: Error executing write: malformed JSON string, neither tag

### ISSUE THREAD

**Issue by leyifoxit** [oetiker/SmokePing#363]
<img width="1050" alt="image" src="https://user-images.githubusercontent.com/128056646/225797517-1d7265ed-1a84-4682-8012-0d795794297b.png">
Targets  config
<img width="554" alt="image" src="https://user-images.githubusercontent.com/128056646/225797730-70370517-168a-4982-9ba7-f2c5f95f9431.png">

Database config
<img width="725" alt="image" src="https://user-images.githubusercontent.com/128056646/225797814-360da902-f063-4f42-a098-2932d20a2c39.png">

how to solve this error ？
@mad-ady

**Comment by leyifoxit** [comment]
<img width="736" alt="image" src="https://user-images.githubusercontent.com/128056646/225799335-7b4d24a6-a244-40f2-bdc6-6db3d2effc67.png">
Targets config
<img width="599" alt="image" src="https://user-images.githubusercontent.com/128056646/225799372-017407ad-b88c-4319-b7ce-29de5ed84da2.png">

**Comment by mad-ady** [comment]
I'd say the first error may indicate the fact that smokeping can't connect to your influxdb server (10.122.126.43).

Check what traffic you have between smokeping and your influxdb server with a packet capture tool like tcpdump. Is it able to establish a connection? Does the database exist in influxdb?

**Comment by leyifoxit** [comment]
<img width="697" alt="image" src="https://user-images.githubusercontent.com/128056646/225840305-d0a5c999-ffc0-4b51-b5b8-1343ae7ce75c.png">

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/128056646/225840374-d4915e07-1b90-4c47-b60e-8c98a7b88cca.png">


<img width="1044" alt="image" src="https://user-images.githubusercontent.com/128056646/225840576-3738c79f-cce3-4376-aa38-39636900c4ca.png">


<img width="809" alt="image" src="https://user-images.githubusercontent.com/128056646/225840635-9bbba8b2-ef3b-44a2-99e0-c19c85103010.png">

**Comment by leyifoxit** [comment]
@mad-ady 
What is the second error and how should I fix it?

**Comment by mad-ady** [comment]
If you're running my docker build, I think it's slightly different than the
main Smokeping build in terms of parsing influx_* config items. I'd try
removing influx_service_type from your config file. Not sure I'll have time
to review my old code, to see what the accepted values were.

**Comment by leyifoxit** [comment]
@mad-ady Thank you, I am waiting for your message
