### ISSUE TITLE
need to update TCPPing doc

### ISSUE THREAD

**Issue by yankaiqian** [oetiker/SmokePing#37]
I tried TCPPing probe few days ago following this page:

http://oss.oetiker.ch/smokeping/probe/TCPPing.en.html

Found that we need to comment out the "tcptraceroute" line in the config file since the latest tcpping script doesn't accept "-e" option:

    #tcptraceroute = -e "sudo /usr/bin/tcptraceroute"

Here is the tcpping script download url:

http://www.vdberg.org/~richard/tcpping

Others also mentioned this issue in the mailing list:
https://lists.oetiker.ch/pipermail/smokeping-users/2014-September/005546.html

**Comment by oetiker** [comment]
maybe it would be worth it to rewrite the probe to use tcptraceroute directly ...

**Comment by elias-p** [comment]
I have updated with the fix but I still can't get data on the chart. the script created one rrd file out side the host directory but that not updated to after created.
 something else I need to check?

**Comment by oetiker** [comment]
for support, please use the smokeping mailinglist ...

**Comment by snghoshi** [comment]
Hi i dont have the binary in the /usr/bin/tcpping directory. how do i add this?

**Comment by ferjaninasraoui** [comment]
@snghoshi

http://xmodulo.com/how-to-install-tcpping-on-linux.html

i hope this could help you

**Comment by snghoshi** [comment]
hi Ferjaninasraoui,

Thanks i got it working. Just a bit weird  in that with the TCPPing even if the link is off or the port you pinging is off the graph sill shows as if its reachable. i.e it still project something on the graph.
