### ISSUE TITLE
Memory leak with custom `Database` settings

### ISSUE THREAD

**Issue by ubuntuyeah** [oetiker/SmokePing#377]
This Database configuration causes the CGI script to consume all available memory and eventually brings the system down... unless the OOM killer gets to it in time. This is on latest smokeping. Desired behavior: either use what is available, or throw an error. 

```
*** Database ***

step     = 7
pings    = 3

# consfn mrhb steps total
AVERAGE  0.5  1  123428
AVERAGE  0.5  1  43800

```

**Comment by oetiker** [comment]
Hmm what would you like to achieve with this setting? Apart from bringing down the system ?
