### ISSUE TITLE
fping help output changed/FPingContinuous does not detect feature

### ISSUE THREAD

**Issue by NBD-Chris** [oetiker/SmokePing#386]
FPingContinuous.pm expects the help output of the fping command to match the pattern "\s-S\s".  The actual help output is now "-S, --src=IP       set source address", so the FPingContinuous module believes that it's not possible to set the source address.

I just changed the pattern to "\s-S[\s,]".

Same problem with the -O option to set the type of service (tos) flag on the ICMP packets.  Same sort of fix.

[smokeping-FPingContinuous.pm.patch](https://github.com/oetiker/SmokePing/files/13492990/smokeping-FPingContinuous.pm.patch)

**Comment by oetiker** [comment]
Hi @NBD-Chris, thank you for your patch. If you directly edit: https://github.com/oetiker/SmokePing/edit/master/lib/Smokeping/probes/FPingContinuous.pm you would even get credit for the fix :) how about it ?
