### ISSUE TITLE
FPingContinuous needs fix due to an incompatible change in the fping5+ output format

### ISSUE THREAD

**Issue by dadv** [oetiker/SmokePing#394]
fping 5.0 (2020-08-05) introduced an incompatible change to its output:

> In non-quiet loop and count mode, a line is printed for every lost packet 

https://github.com/schweikert/fping/blob/develop/CHANGELOG.md#incompatible-changes

In practice, it can produce the following variations:

100.64.0.1 : [10], timed out (NaN avg, 100% loss)
100.64.0.1 : [63], timed out (172 avg, 18% loss)

First one is printed if a target has not responded yet.

FPingContinuous.pm has not adopted to parse this, so it floods its log:

Jan 16 02:54:02 syslog smokeping[99911]: FPingContinuous: Unknown input data:  100.64.0.1 : [10], timed out (NaN avg, 100%% loss)

**Comment by Gunni** [comment]
Still a problem, should be reopened.
