### ISSUE TITLE
Unable to Zoom or Crop Graphs using mouse in 2.8.2

### ISSUE THREAD

**Issue by AIXperts** [oetiker/SmokePing#396]
Hi,

The graphs no longer respond to mouse actions at all. New install of 2.8.2. Is this a know issue or something in the browser?

No, this is not the issue: https://github.com/oetiker/SmokePing/issues/134

Regards,
Henrik Morsing

**Comment by svenvg93** [comment]
Hi, 

Not sure this applies to you, wanted to share it anyways. 
I had the same problem using a third party html page: https://github.com/tsumaru720/smokeping-bootstrap 

It was missing the smokeping-zoom.js file. That is is probably removed in a later version. 
As I couldnt figure out why or which file replaced it. I download the file from an old release; 2.6.8 and move it to the /usr/share/smokeping/www/js folder. Now it works again for me.
