### ISSUE TITLE
/etc/smokeping/config is not managed by puppet

### ISSUE THREAD

**Issue by nkarpin** [oetiker/SmokePing#40]
Hello,

i am using this module in puppet3 and smokeping is set in standalone mode

i have successfully deployed it on the server using puppet and /etc/smokeping/config file was generated as below and all is working great:

@include /etc/smokeping/config.d/General
@include /etc/smokeping/config.d/Alerts
@include /etc/smokeping/config.d/Database
@include /etc/smokeping/config.d/Presentation
@include /etc/smokeping/config.d/Probes
@include /etc/smokeping/config.d/Slaves
@include /etc/smokeping/config.d/Targets

but when i deleted  /etc/smokeping/config i found that it was not recreated when i run puppet,

and i cannot find /etc/smokeping/config in puppet templates or manifests in your module,

can you please look at this and maybe add possibility to manage  /etc/smokeping/config using puppet

thank you!

**Comment by oetiker** [comment]
Please contact the person who created your puppet module. This is the issue tracker for smokeping.
