### ISSUE TITLE
cropper broken, smokeping.js TypeError: window.options is undefined

### ISSUE THREAD

**Issue by FliesLikeABrick** [oetiker/SmokePing#406]
We are running 2.8.2+ from latest git master.

Original issue we were investigating was that the cropper was no longer working.

We saw in network tools in-browser that the expected JS resources were all being downloaded, but an error was in the JS console from smokeping.js line 127 "TypeError: window.options is undefined" 

It appears the latest commit to smokeping.js from January 2023 was adding some auto-refresh capability.  "window.options.step" is being accessed which does not appear to be valid in latest Firefox (and I believe our teammates reported the same issue with Chrome and Edge)

`       }, window.options.step * 1000);`

We reverted to the prior commit of smokeping.js which resolved the issue; we are not sure what functionality is lost as a result

I am not sure the intent of that "window.options.step" reference to propose a fix at this time.

**Comment by FliesLikeABrick** [comment]
@oetiker  care to give this a look?  I think the fix here is fairly simple but I don't know the context of how the issue was introduced to offer it in a PR

**Comment by oetiker** [comment]
probably your base page is missing the script section ... see here:

https://github.com/oetiker/SmokePing/pull/354/files#diff-63d15f54b199e9cacaa1dacb55cf9f4ac4b1c7a33a1041dc199a3e995979987d

**Comment by FliesLikeABrick** [comment]
Thanks, that does appear to be the case - I wonder if we grabbed our snapshot at a time between PRs or something, thank you.
