### ISSUE TITLE
Add option to change probe description in graphs

### ISSUE THREAD

**Issue by kbabioch** [oetiker/SmokePing#43]
Maybe I've missed an option, but as far as I can tell there is no way to change the "probe description" in the graphs generated by SmokePing. At the very bottom it always says:

probe: 20 ICMP Echo Pings (56 bytes) every 300s

This is true for simple ping probes, but what about more sophisticated probes? In my case, for instance, I'm not only pinging my targets, but also have some DNS probes configured. It uses dig in the background and definitely is not sending ICMP packets ;).

There should be a way for each probe to define such a string for itself, and possibly overwrite it with an option in the configuration file.

**Comment by oetiker** [comment]
that must be an issue with your probe ... see http://oss.oetiker.ch/smokeping-demo/?target=SIP for example ... the ProbeDesc method of the probe is responsible for that string.
