### ISSUE TITLE
how should I parse the rrd file?

### ISSUE THREAD

**Issue by linshibo** [oetiker/SmokePing#45]
I wanted to parse the rrd data file and store the loss  in mysql so I can use them later, and I parsed it like this 
`
rrdtool fetch  /opt/smokeping/data/Test/name/xxxxxx.rrd AVERAGE   -s -1days -e now
`
And I got this
`
                         uptime                loss              median               ping1               ping2               ping3               ping4               ping5               ping6               ping7               ping8               ping9              ping10              ping11              ping12              ping13              ping14              ping15              ping16              ping17              ping18              ping19              ping20

1445531400: -nan 6.6666666667e-02 3.2316666667e-03 3.1000000000e-03 3.1086666667e-03 3.1203333333e-03 3.1300000000e-03 3.1310000000e-03 3.1313333333e-03 3.1526666667e-03 3.1530000000e-03 3.1726666667e-03 3.2023333333e-03 3.2316666667e-03 3.2320000000e-03 3.2516666667e-03 3.2620000000e-03 3.2910000000e-03 3.3006666667e-03 4.0983333333e-03 1.1435333333e-02 1.2727666667e-02 1.1380000000e-02
1445531700: -nan 1.9400000000e+00 3.2788000000e-03 -nan 3.0718000000e-03 3.1303000000e-03 3.1309000000e-03 3.1603000000e-03 3.1703000000e-03 3.2285000000e-03 3.2385000000e-03 3.2494000000e-03 3.2688000000e-03 3.2788000000e-03 3.2885000000e-03 3.2991000000e-03 3.3185000000e-03 3.3188000000e-03 3.3188000000e-03 2.5406900000e-02 2.3891420000e-01 2.7595940000e-01 -nan
`
So here is the problem , the loss is  1.9400000000e+00, does it mean the loss rate is 1.94%?
And where can I get some doc  on the meanings of rrd file?

**Comment by langlangago** [comment]
Hello ,have you sloved this problem? I also want to konw the answer.when you see this, pelase contact me . thanks

**Comment by jackitsdotcom** [comment]
I think this is related to an issue I'm having...happens on 2.6.8 and 2.6.11

**Comment by oetiker** [comment]
there is no documentation on this besides the code iteself ...
