### ISSUE TITLE
Problems with slave config on ubuntu

### ISSUE THREAD

**Issue by masonke** [oetiker/SmokePing#46]
smokeping -v
2.006008
For some crazy reason, smokeping claims it cannot open the smokeping_secrets file on the slave. Anyone know what could be wrong? I am running as root, the smokeping_secrets has one word in it.

BTW, the slave config is a nightmare, the docs are so far out of date, it isn't funny

root@xxxxx:/etc/smokeping# smokeping --master-url=http://smoker.yyy.svc/cgi-bin/smokeping.cgi --cache-dir=/var/cache/smokeping --shared-secret=/etc/smokeping/smokeping_secrets --debug --logfile=/tmp/smoke.log
WARNING: Opening secrets file /etc/smokeping/smokeping_secrets: Permission denied

Sent data to Server. Server said WARNING: Opening secrets file /etc/smokeping/smokeping_secrets: Permission denied
ERROR: we did not get config from the master. Maybe we are not configured as a slave for any of the targets on the master ?

-rw-r----- 1 root root    4 Nov  1 15:13 smokeping_secrets

**Comment by freeyoung** [comment]
Just in case if someone encountered the same issue here, please check the permission/ownership of `/etc/smokeping/smokeping_secrets` on your master node instead of the slave nodes.

That file must be readable by your apache2/nginx user (`www-data`) and must not be world-readable. So a quick workaround would be:

```
chown www-data: /etc/smokeping/smokeping_secrets
chmod 640 /etc/smokeping/smokeping_secrets
```

**Comment by Strykar** [comment]
Reading this first would be the correct solution - https://github.com/oetiker/SmokePing/wiki/FAQ
