### ISSUE TITLE
autorefresh resets zoom level

### ISSUE THREAD

**Issue by aspiers** [oetiker/SmokePing#5]
I see that there is now a navigator graph which I can click-drag to zoom - awesome!  (Maybe that's an old feature but I'm not a heavy smokeping user so I only just noticed.)

However, the autorefresh thing every ten seconds or so causes it to reset the zoom to the original level.  Needless to say, this has a significant impact on usability of the feature.  Could it be easily fixed?

**Comment by n0rc** [comment]
Insert the following code at the beginning of function [changeRRDImage](https://github.com/oetiker/SmokePing/blob/master/htdocs/js/smokeping.js#L28):
```javascript
window.stop();
```
This will disable the autorefresh after zooming in.

**Comment by Strykar** [comment]
@oetiker Could this be closed?

**Comment by oetiker** [comment]
@Strykar PR ?

**Comment by Strykar** [comment]
@n0rc Can you post a PR? Your suggested fix isn't working here.

**Comment by n0rc** [comment]
> @n0rc Can you post a PR? Your suggested fix isn't working here.

What exactly is not working? Did you check if your browser recognized your changes in `smokeping.js` (caching etc.)?

I just checked with a fresh installation of smokeping v2.7.3 and it works as expected.
