### ISSUE TITLE
SmokePing Charts Show Wrong Image for Std Dev, Median, Max, Packet Loss, etc.

### ISSUE THREAD

**Issue by ScriptAutomate** [oetiker/SmokePing#50]
System:
Ubuntu 14.04.3 LTS
SmokePing 2.6.8

Issue:
Data seems to be appearing properly on my pages that are configured via the Presentation + detail section of the smokeping config. The issue seems to be when using the default + charts section, for stddev, max, loss, and median. I'm using the following configuration:

menu = Charts
title = The most interesting destinations

++ stddev
sorter = StdDev(entries=>4)
title = Top Standard Deviation
menu = Std Deviation
format = Standard Deviation %f

++ max
sorter = Max(entries=>5)
title = Top Max Roundtrip Time
menu = by Max
format = Max Roundtrip Time %f seconds

++ loss
sorter = Loss(entries=>5)
title = Top Packet Loss
menu = Loss
format = Packets Lost %f

++ median
sorter = Median(entries=>5)
title = Top Median Roundtrip Time
menu = by Median
format = Median RTT %f seconds

The issue here is that the images that appear are the ones generated in /var/cache/smokeping/images/__chartscache -- which only shows a single image existing per Target. The image that is generated only shows a Last Hour latency graph. This image, xxxx_last_3600.png, is referenced in every chart for std dev, median, max, packet loss. 

I'm not sure what to do here to resolve this issue?

**Comment by chrismcmacken** [comment]
Also running into this issue
