### ISSUE TITLE
do_syslog confusion

### ISSUE THREAD

**Issue by mdiehm** [oetiker/SmokePing#53]
Hi, 

I was getting syslogentries like:
Feb 10 08:24:42 urz-noc-tools smokeping[1468]: Alert onelossOver20percent is active for Datacenter.TEST-urz-netgw_short loss: 100%%(3/3) rtt: U prevmatch: 0 comment: loss 1st time

and thought i might have done sth. wrong in my extension for logging but it turns out that the following is responsible for that (why is it like that?):

```
    sub do_syslog ($){
            my $str = shift;
            $str =~ s,%,%%,g;
```

shouldn't it be more like:

  $str =~ s,%%,%,g;

Thx,
-m

**Comment by oetiker** [comment]
oh my ... there seems definitely to be too much cruft in this code ... why is this there at all???

**Comment by mdiehm** [comment]
hehe - I guess someone was seeing %% in the msg (leftovers from rrd parts) and just wanted to make sure... but that's just a guess.

**Comment by oetiker** [comment]
https://tools.ietf.org/html/rfc5424 has one mention of %% in an example but it seems to be just that ... an example ... I would simply remove the magic
