### ISSUE TITLE
I can not access the web interface.

### ISSUE THREAD

**Issue by squintero718** [oetiker/SmokePing#62]
When I open the page www.example.com/cgi-bin/smokeping.cgi  the web interface (SmokePing)  does not appear.

 What should I do ?
Thank you.

Sebastian Quintero.

**Comment by oetiker** [comment]
please follow the install instructions and use the mailinglist for your questions ...

**Comment by squintero718** [comment]
Where I can find the instructions?

**Comment by moetiker** [comment]
http://oss.oetiker.ch/smokeping/doc/index.en.html
