### ISSUE TITLE
TraceroutePing

### ISSUE THREAD

**Issue by GLR81** [oetiker/SmokePing#65]
Is the Probe TraceroutePing supposed to work ?
It doesn't work for me and I am getting this debug output:

```
smokeping[30577]: TraceroutePing: forks 5, timeout for each target 26
smokeping[30579]: TraceroutePing: Host 2.2.8.1
smokeping[30579]: TraceroutePing: Desthost 8.2.1.7
smokeping[30579]: TraceroutePing: validated 2.2.8.1
smokeping[30579]: TraceroutePing: Executing /usr/bin/traceroute -w 1 -f 10 -m 10 -q 1 -n 8.2.1.7
smokeping[30579]: TraceroutePing: stdout: traceroute to 8.2.1.7 (8.2.1.7), 10 hops max, 60 byte packets
smokeping[30579]: TraceroutePing: stdout: 10  2.2.8.1  2.547 ms
smokeping[30579]: TraceroutePing: Executing /usr/bin/traceroute -w 1 -f 10 -m 10 -q 1 -n 8.2.1.7
smokeping[30579]: TraceroutePing: stdout: traceroute to 8.2.1.7 (8.2.1.7), 10 hops max, 60 byte packets
smokeping[30579]: TraceroutePing: stdout: 10  2.2.8.1  2.420 ms
smokeping[30579]: TraceroutePing: Executing /usr/bin/traceroute -w 1 -f 10 -m 10 -q 1 -n 8.2.1.7
smokeping[30579]: TraceroutePing: stdout: traceroute to 8.2.1.7 (8.2.1.7), 10 hops max, 60 byte packets
smokeping[30579]: TraceroutePing: stdout: 10  2.2.8.1  2.393 ms
smokeping[30579]: TraceroutePing: Executing /usr/bin/traceroute -w 1 -f 10 -m 10 -q 1 -n 8.2.1.7
smokeping[30579]: TraceroutePing: stdout: traceroute to 8.2.1.7 (8.2.1.7), 10 hops max, 60 byte packets
smokeping[30579]: TraceroutePing: stdout: 10  2.2.8.1  2.294 ms
smokeping[30579]: TraceroutePing: Executing /usr/bin/traceroute -w 1 -f 10 -m 10 -q 1 -n 8.2.1.7
smokeping[30579]: TraceroutePing: stdout: traceroute to 8.2.1.7 (8.2.1.7), 10 hops max, 60 byte packets
smokeping[30579]: TraceroutePing: stdout: 10  2.2.8.1  2.183 ms
smokeping[30579]: TraceroutePing: Times:
smokeping[30577]: TraceroutePing: 2.2.8.1: got
smokeping[30577]: Calling RRDs::update(/var/lib/smokeping/2-2-8-1.rrd --template uptime:loss:median:ping1:ping2:ping3:ping4:ping5 1469207490:U:5:U:U:U:U:U:U)
smokeping[30577]: TraceroutePing: Sleeping 60 seconds.
```
So the traceroute outputs looks OK but Smokeping not.

**Comment by oetiker** [comment]
it seems that the output of your version of traceroute is not as expected ... hence there is no information on the 'times' line ...

**Comment by GLR81** [comment]
Thanks for the quick reply :-)
I wonder how is it supposed to be then... It is the same output on all traceroutes I can try:
<hop number> <hop ip> <rtt>

**Comment by oetiker** [comment]
reading the parser code (not mine) I can't shake the suspicion that this might be a bit overly complex ... 

`/^\s+\d+\s+\S+\s+(\d|\.|,)+\s+\S+\s*$/` would indicate that only lines starting with at least one space would be accepted ...

**Comment by GLR81** [comment]
I see: it works fine for hops below 10 because the output entries then start with a space.
This is bug in the regex: the first space should be optional.

**Comment by GLR81** [comment]
So for me the right regex is:
`/^\s?\d+\s+\S+\s+(\d|\.|,)+\s+\S+\s*$/`
It then works fine.

**Comment by oetiker** [comment]
can you please try 
5ac48fab69cfb674b0e43153e70444f1caff1a50

**Comment by GLR81** [comment]
It works perfectly. Thanks !
(Very honored to "talk" to the great creator of RRDTool and SmokePing !)

**Comment by cgull** [comment]
I just noticed this.  As the original author of this thing, those changes look good to me.  I originally wrote it to observe a nearby device, only 2 or 3 hops away, so I'm not surprised I never noticed the >10 hops problem.

(And we've moved since then and I no longer need to use this probe at all, of course.)
