### ISSUE TITLE
alertee: error with snpp address

### ISSUE THREAD

**Issue by akriegisch** [oetiker/SmokePing#66]
when adding snpp addresses as alertees, smokeping errors out with 'the alertee must be an email address here'. The reason for this seems to be that whitespaces in the list aren't properly stripped:
`alertee = foo@example.com, snpp:12345`
leads to an error while
`alertee = foo@example.com,snpp:12345`
works fine.
On the other hand, specifying an snpp contact only does not work at all:
`alertee=snpp:12345`
and requires me to change Smokeping.pm like this work:
```
--- /usr/share/perl5/Smokeping.pm       2016-08-31 14:11:41.659624995 +0200
+++ /usr/share/perl5/Smokeping.pm       2016-08-31 15:52:26.639298107 +0200
@@ -2296,7 +2296,7 @@
 DOC
            },

-           alertee => { _re => '(\|.+|.+@\S+|snpp:)',
+           alertee => { _re => '(\|.+|.+@\S+|.*snpp:.+)',
                         _re_error => 'the alertee must be an email address here',
                         _doc => <<DOC },
 If you want to have alerts for this target and all targets below it go to a particular address
```

(I am using smokeping 2.6.9-1+deb8u1 on Debian/Jessie)

**Comment by oetiker** [comment]
how about this

```
   _re => '^(?:\|.+|.+@\S+|snpp:.+)(?:\s*,\s*(?:\|.+|.+@\S+|snpp:.+))*$'
```

**Comment by akriegisch** [comment]
perfect! :) This fixes the issue for me.

**Comment by oetiker** [comment]
3479284
