### ISSUE TITLE
Ubuntu - Issues with Smokeping on 16.04 Upgrade

### ISSUE THREAD

**Issue by sharpy1064** [oetiker/SmokePing#67]
I have smokeping working fine since 15.10. I did the online upgrade to 16.04. 
Smokeping was the only app with errors. It is still running OK, but I get errors during updates, and tried to fix, with no change:

root@mybox# apt-get upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up smokeping (2.6.11-2) ...
dpkg: error processing package smokeping (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 smokeping
E: Sub-process /usr/bin/dpkg returned an error code (1)

root@mybox# apt-get --reinstall install smokeping
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
E: Internal Error, No file name for smokeping:amd64

**Comment by oetiker** [comment]
for ubuntu package issues, please log a bug with ubuntu
