### ISSUE TITLE
basefork

### ISSUE THREAD

**Issue by dallasweitzel** [oetiker/SmokePing#68]
I setup the configuration and it never writes any data.  I get this error in the syslog.

Nov 28 17:53:30 rochlinux1 smokeping[14989]: pingone: this must be overridden by the subclass at /usr/share/perl5/Smokeping.pm line 1722.

I dont know what to do so pingone works

**Comment by oijkn** [comment]
Hi did you find any way to fix this issue, please ? Because i'm in the same case :\

**Comment by dallasweitzel** [comment]
that was so long ago.  I forgot.  I did get it working though.
