### ISSUE TITLE
Per target binary support

### ISSUE THREAD

**Issue by petrus-lt** [oetiker/SmokePing#72]
I'm trying to execute a probe for a given target within a Linux network namespace / FreeBSD fib / OpenBSD rdomain. It does not seem currently possible.

An interesting way would be to be able to define the binary at the Target level, instead of Probe. One could then create a wrapper around the OS way (ip netns exec foo <fping|dig> / route -Tfoo exec). It would allow any probe to be used within a routing instance.

Another way would be to adapt each probe code to use a "instance" variable, but that would require much more work.

Do you think it could be doable?

Thanks.

**Comment by oetiker** [comment]
you can specify the probe 'binary' you can replace the binary by a little shell script doing whatever magic you need ...
