### ISSUE TITLE
Smokeping::probes::DNS ignores retransmissions

### ISSUE THREAD

**Issue by fenner** [oetiker/SmokePing#73]
We're having some pretty serious DNS troubles, and yet our Smokeping::probes::DNS probe is not really showing anything.  It turns out that it completely ignores retransmissions - so the dig subprocess might take 10 seconds to get a reply (since two requests were dropped), but the one response that did succeed got a reply in 20ms, so the total response time is returned as 20ms.

I think the best thing to do here would be to report retransmissions as loss - so, if a query took 20ms but required two retransmissions to be answered, add two to $run.

(Can dig report the number of retransmissions required? I don't know.)

Another thing to do is to time the dig command itself from inside perl.

**Comment by oetiker** [comment]
dig does not seem very forthcoming on these matters ... maybe a probe based on https://metacpan.org/pod/Net::DNS::Lite might be a good thing since it allows to specify timeouts for each retry ... so if it was configured to not retry with a timeout of 10 ...

**Comment by fenner** [comment]
Indeed, I haven't figured out how to get dig to tell us stuff like this.

**Comment by 4f96a64d** [comment]
You may want to try the AnotherDNS probe. 
`timeout = 1 `
Would do a reasonable job at getting long queries to show up as loss on your graphs.
