### ISSUE TITLE
Huge discrepancy between DNS vs AnotherDNS

### ISSUE THREAD

**Issue by goaquin** [oetiker/SmokePing#79]
Hello,
I have a huge discrepancy between AnotherDNS and DNS probes. 
![image](https://cloud.githubusercontent.com/assets/3218329/24514736/b3743ab8-154b-11e7-99ba-2400620561a5.png)
![image](https://cloud.githubusercontent.com/assets/3218329/24514763/ca2cc25c-154b-11e7-83ff-29318d3b60e1.png)
As shown in the images DNS has 10 times more latency than AnnotherDNS.

This is my config:
```
+ DNS

binary = /usr/bin/dig # mandatory
forks = 5
offset = 50%
step = 300
timeout = 15
# The following variables can be overridden in each target section
lookup = www.akainix.com
pings = 5
server = 8.8.8.8

+ AnotherDNS

forks = 5
offset = 50%
step = 300
# The following variables can be overridden in each target section
ipversion = 4
lookup = www.akainix.com
mininterval = 0.5
pings = 5
port = 53
protocol = udp
recordtype = A
require_answers = 0
require_noerror = 0
timeout = 5
```
Regards,
Joaquín Silva

**Comment by oetiker** [comment]
my guess is that with DNS you are measuring the startup delay for dig as well ... but just guessing ...

**Comment by 4f96a64d** [comment]
You are specifying 8.8.8.8 in DNS so you are getting the RTT between you, google, the authoritative server and back. AnotherDNS is probably using the local resolver as defined by your OS.
Are you trying to measure the latency of the authoritative server itself or more of a user level experience when people try and reach that domain?
