### ISSUE TITLE
FPing feature detection does not work

### ISSUE THREAD

**Issue by ooneed** [oetiker/SmokePing#90]
in [FPing.pm](https://github.com/oetiker/SmokePing/blob/master/lib/Smokeping/probes/FPing.pm#L70) we see the following code:
```
$self->{enable}{S} = (`$binary -h 2>&1` =~ /\s-S\s/);
$self->{enable}{O} = (`$binary -h 2>&1` =~ /\s-O\s/);
```
The regular expression always fails.
Let's have a look at the current source of fping: In [fping.c](https://github.com/schweikert/fping/blob/develop/src/fping.c#L2737) we see:

`fprintf(out, "   -S, --src=IP       set source address\n");
`
Notice the comma after the -S, it does not match the \s.

I propose the change the regular expressions in FPing.pm to /\s-S[\s,]/ and /\s-O[\s,]/ respectively.

**Comment by oetiker** [comment]
thanks!
