### ISSUE TITLE
OpenSSHJunOSPing.pm - Net:OpenSSH ctl_dir "permission" issue

### ISSUE THREAD

**Issue by moxli** [oetiker/SmokePing#92]
Today I encountered the following error in my syslog:

```
Jul 20 09:55:34 monitor smokeping[24588]: OpenSSHJunOSPing connecting <ip>: ctl_dir /var/lib/smokeping/.libnet-openssh-perl/ is not secure
Jul 20 09:55:35 monitor smokeping[24594]: OpenSSHJunOSPing connecting <ip>: ctl_dir /var/lib/smokeping/.libnet-openssh-perl/ is not secure
```
After researching the [Net:OpenSSH documentation](http://search.cpan.org/~salva/Net-OpenSSH-0.74/lib/Net/OpenSSH.pm) I found out that you use Net:OpenSSH's default for "ctl_dir".

> ctl_dir => $path
> Directory where the SSH master control socket will be created.
> This directory and its parents must be writable only by the current effective user or root, otherwise the connection will be aborted to avoid insecure operation.
> By default **~/.libnet-openssh-perl** is used.

So a .libnet-openssh-perl directory is created in /var/lib/smokeping (smokeping home) and due to the strict_mode method (default = 1) the script fails.

> strict_mode => 0
> By default, the connection will be aborted if the path to the socket used for multiplexing is found to be non-secure (for instance, **when any of the parent directories is writable by other users**).
> This option can be used to disable that feature. Use with care!!!

I assume it fails because some user has write permissions to a other directory in /var or /var/lib.

This leaves me with two options, either setting strict_mode to 0 or creating a directory for the smokeping user in /home and write create the .libnet-open-perl directory there, both seem to work.

```
my $ssh = Net::OpenSSH->new(
        $source,
        $login ? ( user => $login ) : (),
        $password ? ( password => $password ) : (),
        timeout => 60,
#       strict_mode => 0,
#       ctl_dir => "/home/smokeping/.libnet-openssh-perl"
    );
```

Please let me know if I did anything wrong or how I can help improving Smokeping, because this is my first issue ever.

**Comment by oetiker** [comment]
maybe it would make sense to create a user specific directory in /tmp and chmod 700 it ... and then point ctl_dir there ...

**Comment by moxli** [comment]
Works perfectly.
Have you considered adding this one line of code? 
I was not able to make the probe work at all without the "fix".

**Comment by oetiker** [comment]
I'll be glad to look at any PR you submit :) I do not use the module myself, so testing is a bit difficult for me.

**Comment by moxli** [comment]
As a temporary solution I just set the ctl_dir to "/tmp/.libnet-openssh-perl".
As you said earlier, it would be better to have a user specific directory in /tmp. 
Since /tmp is regularly (usually on boot) cleared I need to check if the directory already exists and if not create it when Smokeping launches.
I am just not sure WHERE the best place to do something like this is? 
Can you advice please, I pretty inexperienced...

**Comment by oetiker** [comment]
I would do this right before creating the Net::OpenSSH instance ...

**Comment by moxli** [comment]
I finally was able to get some free time for more testing.
On two fresh installed systems I did not encounter this error.
I rechecked the permissions on our production system and neither /var, /var/lib nor /var/lib/smokeping are writable by other users than smokeping and root.
For now I just added a new probe section on the FAQ page because this looks like an uncommon problem.
