### ISSUE TITLE
Web content missing

### ISSUE THREAD

**Issue by tilverjo** [oetiker/SmokePing#93]
Hi!
I had faced with this trouble after apache22 replaced to apache24. Webpage consists now only

#!/bin/sh
exec /usr/local/bin/smokeping_cgi /usr/local/etc/smokeping/config

instead of spoken graphs&menues.
Could you advice please.

**Comment by oetiker** [comment]
tilvero this will be because fastcgi support is not active in your apache config ... you have to fix your apache config ...

**Comment by tilverjo** [comment]
Thanks a lot,
It was solved by installing the mod_fcgid from port and putting that info into apache config
