### ISSUE TITLE
Changed config is not pushed to slaves

### ISSUE THREAD

**Issue by aretaja** [oetiker/SmokePing#94]
Happens at least on Debian because master config file (/etc/smokeping/config) uses only includes. Smokeping.pm load_cfg method checks only mtime of submitted config file which is not changed:
my $cfmod = (stat $cfgfile)[9].
So we should change mtime of this file on every config change to make  slave config updates happen.

**Comment by oetiker** [comment]
yes ... or teach smokeping to monitor all the includes ...

**Comment by aretaja** [comment]
Maybe better approach should be checksum of parsed confiig or something like that?

**Comment by oetiker** [comment]
the problem is not detecting elusive changes ... but looking at ALL files to see if the timestamp of any of them has changed.

**Comment by computercolin** [comment]
Would love to see this addressed. It seems that if Smokeping allows @include it should not be a regression in functionality. Right now using @include removes Smokeping ability to detect Targets changes (a regression).

(Workaround is to `touch` root config file. But it is not obvious that you would need to do this.)

**Comment by oetiker** [comment]
any plans to work on such a feature ?
