### ISSUE TITLE
debian no longer ships a fping6 binary

### ISSUE THREAD

**Issue by normanr** [oetiker/SmokePing#95]
I upgraded to fping v4 on my debian machine and noticed that all my FPing6 probes stopped working.  I ended up making two tiny fping4/fping6 scripts to pass -4/-6 to fping, but it would be nice to be able to set protocol version in FPing probe settings and not use wrapper scripts.

**Comment by oetiker** [comment]
I agree ... care to provide a patch ?

**Comment by lelutin** [comment]
@oetiker would a patch adding a config option for the probes FPing and FPing6 probes that "enforces protocol" that would then add the parameters to the binary calls be what you had in mind, or should be just change the calls directly and not care to make it configurable?

**Comment by oetiker** [comment]
how about a patch that makes the FPing probe with the current version of fping ? we then would not need Fping6 anymore.

**Comment by hb9eue** [comment]
Hit same issue... I would suggest you update the documentation with the new protocol option: https://oss.oetiker.ch/smokeping/probe/FPing.en.html
