### ISSUE TITLE
 unknown variable 'lookup'

### ISSUE THREAD

**Issue by Owned67** [oetiker/SmokePing#99]
Hello,

debian 9 x64
apt install smokeping

ERROR: /etc/smokeping/config.d/conf_free_serveurs, line 10: unknown variable 'lookup'

Targets:
`*** Targets ***

probe = FPing

menu = Top
title = SmokePing PC
remark = Exemple d'un graphe SmokePing

@include /etc/smokeping/config.d/conf_speedtest
@include /etc/smokeping/config.d/conf_free_serveurs
@include /etc/smokeping/config.d/conf_opendns`

conf_free_serveurs:
`+ DNS
menu = DNS
title = Etat des DNS Free primaire/secondaire

++ DNSFREE1
probe = TCPPing
menu = DNS Free Primaire
title = Etat DNS Free Primaire
host = 212.27.40.240
lookup = free.fr
server = ns1.proxad.net

++ DNSFREE2
probe = TCPPing
menu = DNS Free Secondaire 
title = Etat DNS Free Secondaire
host = 212.27.40.241
lookup = free.fr
server = ns2.proxad.net`

Probes:
`*** Probes ***

+ FPing
binary = /usr/bin/fping
offset = 0%

+DNS
binary = /usr/bin/dig
forks = 1
offset = 70%

#+ FPing6
#binary = /usr/bin/fping6
#offset = 40%

+TCPPing
binary = /usr/bin/tcpping
forks = 5
offset = 50%
step = 300
tcptraceroute = -e "sudo /bin/tcptraceroute"
timeout = 15
pings = 5
#port = 80

+ EchoPingDNS # DNS (53/udp or tcp) servers
binary = /usr/bin/echoping
forks = 5
offset = 50%
step = 300
`

how to fix this error please?

edit:

> apt install lookup
 Lecture des listes de paquets... Fait
 Construction de l'arbre des dépendances
 Lecture des informations d'état... Fait
 lookup is already the newest version (1.08b-11+b2).
 0 mis à jour, 0 nouvellement installés, 0 à enlever et 0 non mis à jour.

**Comment by oetiker** [comment]
check out https://oss.oetiker.ch/smokeping/doc/smokeping_config.en.html for valid configuration options ...
